/* Modelo compartilhado pela interface e pelos testes. Não grava dados ao migrar. */
(function(root,factory){const api=factory();if(typeof module==='object')module.exports=api;else root.SchoolModel=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
  'use strict';
  const GOAL=1065,clone=x=>JSON.parse(JSON.stringify(x)),num=x=>Number.isFinite(Number(x))?Number(x):0;
  const LEGACY_CORE_CLASSES=['G2','G3','G4','G5','1º Ano','2º Ano','3º Ano','4º Ano','5º Ano','6º Ano','7º Ano','8º Ano','9º Ano','1º Ano do Ensino Médio','2º Ano do Ensino Médio','3º Ano do Ensino Médio'];
  const REPORT_2027_ROWS=[
    ['Educação Infantil','G2 A',18,9,9],['Educação Infantil','G2 B',18,0,0],['Educação Infantil','G3 A',24,17,2],['Educação Infantil','G3 B',24,16,4],['Educação Infantil','G4 A',25,30,3],['Educação Infantil','G4 B',26,16,0],['Educação Infantil','G5 A',21,22,1],['Educação Infantil','G5 B',18,0,0],['Educação Infantil','G5 C',22,14,2],
    ['Fundamental Anos Iniciais','1º A',25,18,0],['Fundamental Anos Iniciais','1º B',19,17,3],['Fundamental Anos Iniciais','1º C',25,12,0],['Fundamental Anos Iniciais','1º D',19,8,1],['Fundamental Anos Iniciais','2º A',24,18,0],['Fundamental Anos Iniciais','2º B',19,11,0],['Fundamental Anos Iniciais','2º C',19,10,0],['Fundamental Anos Iniciais','2º D',24,5,1],['Fundamental Anos Iniciais','3º A',25,17,0],['Fundamental Anos Iniciais','3º B',25,16,0],['Fundamental Anos Iniciais','3º C',25,9,0],['Fundamental Anos Iniciais','3º D',25,11,0],['Fundamental Anos Iniciais','4º A',35,17,0],['Fundamental Anos Iniciais','4º B',15,18,1],['Fundamental Anos Iniciais','4º C',35,20,0],['Fundamental Anos Iniciais','5º A',30,26,0],['Fundamental Anos Iniciais','5º B',27,13,0],['Fundamental Anos Iniciais','5º C',30,12,0],
    ['Fundamental Anos Finais','6º A',35,12,0],['Fundamental Anos Finais','6º B',26,16,0],['Fundamental Anos Finais','6º C',35,16,0],['Fundamental Anos Finais','7º A',30,43,0],['Fundamental Anos Finais','7º B',30,6,0],['Fundamental Anos Finais','8º A',35,19,0],['Fundamental Anos Finais','8º B',28,0,0],['Fundamental Anos Finais','8º C',28,9,0],['Fundamental Anos Finais','9º A',30,12,0],['Fundamental Anos Finais','9º B',28,9,0],['Fundamental Anos Finais','9º C',30,8,0],
    ['Ensino Médio','1º EM',48,40,0],['Ensino Médio','2º EM',43,25,0],['Ensino Médio','3º EM',35,27,0]
  ];
  const CORE_CLASSES=REPORT_2027_ROWS.map(([,name])=>name);
  const FINANCIAL_SEGMENTS=[['early','Educação Infantil'],['fundamental1','Fundamental I'],['fundamental2','Fundamental II'],['secondary12','1º e 2º ano do Ensino Médio'],['secondary3','3º ano do Ensino Médio']];
  const FINANCIAL_CATEGORIES=[['noDiscount','Sem desconto',0],['philanthropic100','Bolsa filantrópica',100],['philanthropic50','Bolsa filantrópica',50],['staffChild100','Filho de funcionário',100],['staffChild80','Filho de funcionário',80],['workerChild100','Filho de obreiro',100],['markingLives45','Projeto Marcando Vidas',45]];
  const INITIAL_TUITION={early:930.69,fundamental1:964.67,fundamental2:1239.81,secondary12:1425.59,secondary3:1461.05};
  const integer=x=>Number.isSafeInteger(Number(x))&&Number(x)>=0;
  const modules=['dashboard','enrollments','classes','benefits','requests','budget','delinquency','guardians','users','reports','tasks','team','financial'];
  const fold=x=>String(x??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
  function templateId(name){return 'caj-'+fold(name).replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');}
  function reportClasses(){return REPORT_2027_ROWS.map(([stage,name,capacity,students,fresh])=>({id:'caj-2027-'+templateId(name),name,stage,capacity,opening:{new:fresh,re:students-fresh},unclassified:0,students,template:false,source:'Matrículas 2027 CAJ'}));}
  function emptyGeneric(c){return c.template===true&&num(c.capacity)===0&&num(c.students)===0&&num(c.opening?.new)===0&&num(c.opening?.re)===0&&num(c.unclassified)===0;}
  function canReplaceGenericClasses(s){const names=s.classes.map(c=>fold(c.name)).sort(),legacy=LEGACY_CORE_CLASSES.map(fold).sort(),history=s.enrollments?.history||[];return names.length===legacy.length&&names.every((name,index)=>name===legacy[index])&&s.classes.every(emptyGeneric)&&history.length===0&&num(s.enrollments?.new)===0&&num(s.enrollments?.re)===0&&num(s.enrollments?.unallocated?.new)===0&&num(s.enrollments?.unallocated?.re)===0;}
  function ensureCoreClasses(s){const history=s.enrollments?.history||[],noEnrollmentData=!history.length&&num(s.enrollments?.new)===0&&num(s.enrollments?.re)===0&&num(s.enrollments?.unallocated?.new)===0&&num(s.enrollments?.unallocated?.re)===0;if((!s.classes.length&&noEnrollmentData)||canReplaceGenericClasses(s))s.classes=reportClasses();return s;}
  function migrate(input){
    const s=clone(input||{});for(const k of ['classes','benefits','requests','budget','guardians','imports','tasks','users','audit','notifications','classificationRules','reviewQueue'])if(!Array.isArray(s[k]))s[k]=[];
    s.enrollments=s.enrollments||{new:0,re:0,history:[]};s.enrollments.history=s.enrollments.history||[];s.delinquency=s.delinquency||{};
    if(Number(s.schemaVersion||0)<2){
      s.migration={date:new Date().toISOString(),previousGoal:s.meta??null,legacyEnrollmentTotals:{new:num(s.enrollments.new),re:num(s.enrollments.re)}};
      for(const c of s.classes){const h=s.enrollments.history.filter(x=>String(x.classId)===String(c.id));const known=h.reduce((a,x)=>a+num(x.quantity),0);c.opening=c.opening||{new:0,re:0};c.unclassified=Math.max(0,num(c.students)-known);c.legacyStudents=num(c.students);}
      const assigned=type=>s.enrollments.history.filter(x=>x.type===type&&s.classes.some(c=>String(c.id)===String(x.classId))).reduce((a,x)=>a+num(x.quantity),0);
      s.enrollments.unallocated={new:Math.max(0,num(s.enrollments.new)-assigned('new')),re:Math.max(0,num(s.enrollments.re)-assigned('re'))};
      s.delinquency.legacyAmounts={financial:s.delinquency.financial??null,accounting:s.delinquency.accounting??null};
      s.delinquency.financialPercent=null;s.delinquency.accountingPercent=null;s.delinquency.monthly=[];
      for(const u of s.users){if(!u.id)u.id='legacy-'+fold(u.name).replace(/[^a-z0-9]/g,'');u.active=u.active!==false;if(fold(u.name)==='livia'){const access=u.access&&typeof u.access==='object'?u.access:{enrollments:['view','create','edit'],benefits:['view','create','edit'],requests:['view','create','edit']},merge=(module,actions)=>[...new Set([...(access[module]||[]),...actions])];u.access={...access,enrollments:merge('enrollments',['view','create','edit']),classes:merge('classes',['view'])};}}
      for(const k of ['imports','classificationRules','reviewQueue'])for(const item of s[k])if(!item.id)item.id=cryptoId();
    }
    if(!integer(s.meta)||num(s.meta)<=0)s.meta=GOAL;ensureCoreClasses(s);ensureFinancialYears(s);if(!s.breakEven||typeof s.breakEven!=='object')s.breakEven={plans:[]};if(!Array.isArray(s.breakEven.plans))s.breakEven.plans=[];for(const plan of s.breakEven.plans){plan.version=integer(plan.version)?num(plan.version):1;plan.status=plan.status||'analysis';for(const key of ['plannedClasses','costCenters','extractions','scenarios','tuitionParameters'])if(!Array.isArray(plan[key]))plan[key]=[];plan.delinquency=plan.delinquency&&typeof plan.delinquency==='object'?plan.delinquency:{officialPercent:plan.officialTotals?.delinquencyPercent??null,scenarioPercent:null};plan.installments=integer(plan.installments)&&num(plan.installments)>0?num(plan.installments):11;plan.enrollmentRule=plan.enrollmentRule||{status:'pending_validation',discountPercent:null};plan.officialBudget=plan.officialBudget&&typeof plan.officialBudget==='object'?plan.officialBudget:{status:'pending_import',classRows:[],totals:{}};if(!Array.isArray(plan.officialBudget.classRows))plan.officialBudget.classRows=[];plan.officialBudget.totals=plan.officialBudget.totals&&typeof plan.officialBudget.totals==='object'?plan.officialBudget.totals:{};plan.managerialPlanning=plan.managerialPlanning&&typeof plan.managerialPlanning==='object'?plan.managerialPlanning:{status:'draft',installments:plan.installments,scenarios:[]};}s.schemaVersion=4;return s;
  }
  function defaultFinancialYear(year,seed=false){return {id:String(year),year:Number(year),parameters:FINANCIAL_SEGMENTS.map(([id,label])=>({id,label,tuition:seed?INITIAL_TUITION[id]:null})),classifications:{}};}
  function ensureFinancialYears(s){if(!Array.isArray(s.academicYears))s.academicYears=[];if(!s.academicYears.some(x=>Number(x.year)===2027))s.academicYears.push(defaultFinancialYear(2027,true));for(const y of s.academicYears){y.id=String(y.id||y.year);y.year=Number(y.year);if(!Array.isArray(y.parameters))y.parameters=defaultFinancialYear(y.year,false).parameters;y.classifications=y.classifications&&typeof y.classifications==='object'?y.classifications:{};for(const p of y.parameters){if(!FINANCIAL_SEGMENTS.some(([id])=>id===p.id))continue;p.label=FINANCIAL_SEGMENTS.find(([id])=>id===p.id)[1];p.tuition=p.tuition===''||p.tuition==null?null:num(p.tuition);}}if(!integer(s.academicDataYear))s.academicDataYear=2027;if(!integer(s.activeAcademicYear)||!s.academicYears.some(y=>y.year===s.activeAcademicYear))s.activeAcademicYear=2027;}
  function segmentForClass(c){if(c.stage==='Educação Infantil')return 'early';if(c.stage==='Fundamental Anos Iniciais')return 'fundamental1';if(c.stage==='Fundamental Anos Finais')return 'fundamental2';return String(c.name).startsWith('3º')?'secondary3':'secondary12';}
  function financialYear(s,year){ensureFinancialYears(s);return s.academicYears.find(x=>x.year===Number(year||s.activeAcademicYear));}
  function classificationFor(s,c,year){const y=financialYear(s,year),raw=y?.classifications?.[c.id]||{},fixed=raw.fixed&&typeof raw.fixed==='object'?raw.fixed:{},variables=Array.isArray(raw.variables)?raw.variables:[];return {fixed,variables};}
  function financialStats(s,c,year){const academic=classStats(s,c),y=financialYear(s,year),segment=segmentForClass(c),tuition=y?.parameters?.find(x=>x.id===segment)?.tuition;const classified=classificationFor(s,c,y?.year),groups=[...FINANCIAL_CATEGORIES.map(([id,label,percent])=>({id,label,percent,quantity:num(classified.fixed[id])})),...classified.variables.map(x=>({id:x.id||cryptoId(),label:'Outros descontos variáveis',percent:num(x.percent),quantity:num(x.quantity)}))];const classifiedCount=groups.reduce((a,x)=>a+x.quantity,0),unclassified=Math.max(0,academic.total-classifiedCount),knownGross=tuition==null?0:classifiedCount*tuition,discounts=tuition==null?0:groups.reduce((a,x)=>a+x.quantity*tuition*x.percent/100,0),net=knownGross-discounts,paying=groups.filter(x=>x.percent<100).reduce((a,x)=>a+x.quantity,0),fullExempt=groups.filter(x=>x.percent===100).reduce((a,x)=>a+x.quantity,0),partial=groups.filter(x=>x.percent>0&&x.percent<100).reduce((a,x)=>a+x.quantity,0),noDiscount=num(classified.fixed.noDiscount);return {...academic,id:c.id,name:c.name,year:y?.year,segment,segmentLabel:y?.parameters?.find(x=>x.id===segment)?.label||segment,tuition:tuition==null?null:num(tuition),groups,classified:classifiedCount,unclassifiedFinancial:unclassified,potential:tuition==null?null:academic.total*tuition,knownGross,discounts,net,ticket:classifiedCount?net/classifiedCount:0,averageDiscount:knownGross?discounts/knownGross*100:0,paying,fullExempt,partial,noDiscount};}
  function financialTotals(s,year,classes=s.classes){const rows=classes.map(c=>financialStats(s,c,year)),sum=field=>rows.reduce((a,x)=>a+num(x[field]),0);return {rows,potential:rows.some(x=>x.potential==null)?null:sum('potential'),discounts:sum('discounts'),net:sum('net'),classified:sum('classified'),unclassifiedFinancial:sum('unclassifiedFinancial'),paying:sum('paying'),fullExempt:sum('fullExempt'),partial:sum('partial'),noDiscount:sum('noDiscount'),ticket:sum('classified')?sum('net')/sum('classified'):0,averageDiscount:sum('knownGross')?sum('discounts')/sum('knownGross')*100:0};}
  function classStats(s,c){const history=(s.enrollments?.history||[]).filter(x=>String(x.classId)===String(c.id));const count=type=>num(c.opening?.[type])+history.filter(x=>x.type===type).reduce((a,x)=>a+num(x.quantity),0);const fresh=count('new'),re=count('re'),unclassified=num(c.unclassified),total=fresh+re+unclassified,capacity=num(c.capacity),excess=Math.max(0,total-capacity);return {new:fresh,re,total,capacity,vacancies:Math.max(0,capacity-total),excess,unclassified,occupancy:capacity>0?total/capacity*100:total>0?null:0,status:excess?'above':total===capacity&&capacity>0?'full':capacity>0&&total/capacity>=.9?'attention':'normal'};}
  function totals(s){const all=s.classes.map(c=>classStats(s,c)),goal=integer(s.meta)&&num(s.meta)>0?num(s.meta):GOAL;const fresh=all.reduce((a,c)=>a+c.new,0)+num(s.enrollments?.unallocated?.new),re=all.reduce((a,c)=>a+c.re,0)+num(s.enrollments?.unallocated?.re),total=all.reduce((a,c)=>a+c.total,0)+num(s.enrollments?.unallocated?.new)+num(s.enrollments?.unallocated?.re),capacity=all.reduce((a,c)=>a+c.capacity,0);return {new:fresh,re,total,goal,percent:total/goal*100,missing:Math.max(0,goal-total),excessGoal:Math.max(0,total-goal),capacity,vacancies:capacity-total,excess:all.reduce((a,c)=>a+c.excess,0),unclassified:all.reduce((a,c)=>a+c.unclassified,0),unallocated:num(s.enrollments?.unallocated?.new)+num(s.enrollments?.unallocated?.re),attention:all.filter(c=>c.status==='attention').length,full:all.filter(c=>c.status==='full').length,above:all.filter(c=>c.status==='above').length};}
  function recalculate(s){for(const c of s.classes)c.students=classStats(s,c).total;const t=totals(s);s.enrollments.new=t.new;s.enrollments.re=t.re;s.meta=t.goal;return s;}
  function permitted(user,module,action='view'){if(!user||user.active===false||user.deleted)return false;if(user.isAdmin)return true;return Array.isArray(user.access?.[module])&&user.access[module].includes(action);}
  function validate(s,previous){
    if(!integer(s.meta)||num(s.meta)<=0)throw Error('Meta: informe uma quantidade inteira positiva.');
    for(const c of s.classes){if(!c.name?.trim()||!integer(c.capacity)||!integer(c.opening?.new||0)||!integer(c.opening?.re||0)||!integer(c.unclassified||0))throw Error('Turma: informe nome e quantidades inteiras não negativas.');}
    for(const h of s.enrollments.history){if(!integer(h.quantity)||num(h.quantity)<1||!['new','re'].includes(h.type)||!/^\d{4}-\d{2}-\d{2}$/.test(h.date))throw Error('Lançamento: quantidade inteira positiva, tipo e data são obrigatórios.');}
    for(const b of s.benefits)if(!b.name?.trim()||!integer(b.quantity))throw Error('Benefício: informe nome e quantidade inteira.');
    for(const r of s.requests){if(!r.title?.trim())throw Error('Informe o título da solicitação.');if(r.status==='rejected'&&!r.rejectionReason?.trim()&&JSON.stringify(r)!==JSON.stringify(previous?.requests?.find(x=>String(x.id)===String(r.id))))throw Error('O motivo da reprovação é obrigatório.');}
    for(const b of s.budget)if(!b.category?.trim()||!Number.isFinite(Number(b.budget))||num(b.budget)<0||num(b.actual)<0)throw Error('Orçamento: conta e valores não negativos são obrigatórios.');
    for(const field of ['financialPercent','accountingPercent']){const v=s.delinquency[field];if(v!=null&&(!Number.isFinite(Number(v))||v<0||v>100))throw Error('Percentuais devem estar entre 0 e 100.');}
    ensureFinancialYears(s);if(new Set(s.academicYears.map(y=>y.year)).size!==s.academicYears.length||s.academicYears.some(y=>!integer(y.year)||y.year<2000||y.year>2100))throw Error('Ano letivo inválido.');for(const y of s.academicYears){if(y.parameters.length!==FINANCIAL_SEGMENTS.length||y.parameters.some(p=>!FINANCIAL_SEGMENTS.some(([id])=>id===p.id)||p.tuition!=null&&(!Number.isFinite(Number(p.tuition))||Number(p.tuition)<0)))throw Error('Parâmetros financeiros inválidos.');for(const c of s.classes){const f=classificationFor(s,c,y.year),fixedValid=FINANCIAL_CATEGORIES.every(([id])=>integer(f.fixed[id]??0)),total=[...FINANCIAL_CATEGORIES.map(([id])=>num(f.fixed[id])),...f.variables.map(x=>num(x.quantity))].reduce((a,x)=>a+x,0);if(!fixedValid||f.variables.some(x=>!integer(x.quantity)||!Number.isFinite(Number(x.percent))||x.percent<0||x.percent>100)||total>classStats(s,c).total)throw Error('Classificação financeira excede os alunos matriculados da turma.');}}
    return true;
  }
  function changes(before,after){const out={};for(const k of ['meta','classes','enrollments','benefits','requests','budget','delinquency','guardians','tasks','imports','classificationRules','reviewQueue','academicYears','activeAcademicYear','academicDataYear','breakEven','revenuePlanning'])if(JSON.stringify(before[k])!==JSON.stringify(after[k]))out[k]=after[k];return out;}
  function auditDiff(before,after,actor,module,action){const events=[],date=new Date().toISOString();for(const [field,value] of Object.entries(after||{}))if(JSON.stringify(before?.[field])!==JSON.stringify(value))events.push({id:cryptoId(),userId:actor.id,user:actor.name,module,action,date,field,before:before?.[field]??null,after:value});return events;}
  function cryptoId(){return typeof crypto!=='undefined'&&crypto.randomUUID?crypto.randomUUID():String(Date.now())+'-'+Math.random().toString(36).slice(2);}
  return {GOAL,CORE_CLASSES,REPORT_2027_ROWS,FINANCIAL_SEGMENTS,FINANCIAL_CATEGORIES,modules,clone,num,fold,integer,migrate,classStats,totals,defaultFinancialYear,ensureFinancialYears,segmentForClass,financialYear,classificationFor,financialStats,financialTotals,recalculate,permitted,validate,changes,auditDiff,cryptoId};
});
