/* Evolução incremental. A chave e os quantitativos legados são preservados. */
'use strict';
const pct=(value,total)=>total>0?value/total*100:0;
const formatPct=value=>`${value.toLocaleString('pt-BR',{maximumFractionDigits:1})}%`;
const dateLabel=value=>/^\d{4}-\d{2}-\d{2}$/.test(value||'')?new Date(value+'T12:00:00').toLocaleDateString('pt-BR'):'—';
const modulePermission={enrollments:'Editar matrículas',classes:'Editar turmas',benefits:'Editar benefícios',requests:'Editar solicitações',budget:'Editar orçamento',delinquency:'Editar inadimplência',guardians:'Editar responsáveis',users:'Administrar usuários'};
function canEdit(module=page){const user=S.users[0];return !modulePermission[module]||user?.permissions?.includes(modulePermission[module])||user?.permissions?.includes('Administrar usuários');}
let committedState=JSON.stringify(S), storageProblem=false;
try { const raw=localStorage.getItem(key); if(raw)JSON.parse(raw); } catch { storageProblem=true; }
function persistState(){
  try{
    if(storageProblem)throw new Error('O armazenamento existente está ilegível. Exporte uma cópia e recupere os dados antes de salvar.');
    const previous=localStorage.getItem(key);
    if(previous && previous!==JSON.stringify(S))localStorage.setItem(key+'_backup',previous);
    localStorage.setItem(key,JSON.stringify(S)); committedState=JSON.stringify(S);
  }catch(error){S=normalizeState(JSON.parse(committedState));toast('Não foi possível salvar. Os dados anteriores foram preservados.');throw error;}
}
function totals(){
  const enrolled=students(), seats=capacity(), planned=S.budget.reduce((sum,x)=>sum+n(x.budget),0),actual=S.budget.reduce((sum,x)=>sum+n(x.actual),0);
  return {enrolled,seats,vacancies:S.classes.reduce((sum,x)=>sum+Math.max(0,n(x.capacity)-n(x.students)),0),excess:S.classes.reduce((sum,x)=>sum+Math.max(0,n(x.students)-n(x.capacity)),0),occupancy:pct(enrolled,seats),planned,actual,remaining:planned-actual,goal:n(S.meta),goalPercent:pct(enrolled,n(S.meta)),missing:Math.max(0,n(S.meta)-enrolled),late:S.requests.filter(x=>x.due&&x.due<localDate()&&!['completed','rejected'].includes(x.status)).length};
}
function meter(value,tone=''){return `<div class="progress ${tone}" role="img" aria-label="${formatPct(value)}"><i style="width:${Math.max(0,Math.min(100,value))}%"></i></div>`;}
function emptyState(title,detail,action=''){return `<div class="empty"><b>${title}</b><p>${detail}</p>${action}</div>`;}
function go(target){page=target;render();$('#page').focus();}
function card(title,body,link=''){return `<section class="card"><div class="card-head"><h2>${title}</h2>${link}</div>${body}</section>`;}
function dashboard(){
  const t=totals(),history=S.enrollments.history, newCount=n(S.enrollments.new),reCount=n(S.enrollments.re);
  const attention=S.classes.filter(x=>occ(x)>=90).sort((a,b)=>occ(b)-occ(a));
  const months=Array.from({length:6},(_,i)=>{const d=new Date();d.setDate(1);d.setMonth(d.getMonth()-5+i);const prefix=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;return {label:d.toLocaleDateString('pt-BR',{month:'short'}),new:history.filter(x=>x.date.startsWith(prefix)&&x.type==='new').reduce((a,x)=>a+n(x.quantity),0),re:history.filter(x=>x.date.startsWith(prefix)&&x.type==='re').reduce((a,x)=>a+n(x.quantity),0)};});
  const max=Math.max(1,...months.map(x=>x.new+x.re));
  const chart=history.length?`<div class="legend"><span><i></i>Novas</span><span><i class="yellow"></i>Rematrículas</span></div><div class="chart" role="img" aria-label="Lançamentos mensais dos últimos seis meses">${months.map(x=>`<div class="chart-column"><b>${x.new+x.re}</b><div class="chart-track" title="${e(x.label)}: ${x.new} novas, ${x.re} rematrículas"><i style="height:${x.re/max*100}%;background:var(--yellow)"></i><i style="height:${x.new/max*100}%"></i></div><small>${e(x.label)}</small></div>`).join('')}</div><p class="hint">Histórico datado dos últimos 6 meses. Os cards incluem todos os totais registrados.</p>`:emptyState('Sem lançamentos no histórico','Registre matrículas e rematrículas para acompanhar a evolução mensal.',btn('Abrir matrículas',"go('enrollments')",'alt small'));
  const alerts=[...attention.map(x=>`${e(x.name)}: ${formatPct(occ(x))} de ocupação.`),...(t.late?[`${t.late} solicitação(ões) com prazo vencido.`]:[]),...(t.actual>t.planned?['Despesas excedem o orçamento em '+money(t.actual-t.planned)+'.']:[]),...(n(S.delinquency.debt)>0?['Dívida informada: '+money(S.delinquency.debt)+'.']:[])];
  return head('Painel Executivo','Indicadores consolidados · '+new Date().toLocaleDateString('pt-BR'),`<div class="head-actions"><span class="local-badge">Dados deste navegador</span>${btn('Relatórios',"go('reports')",'alt')}${btn('Registrar matrícula',"go('enrollments')")}</div>`)
    +metrics([['Alunos matriculados',t.enrolled,`${S.classes.length} turmas cadastradas`],['Novas matrículas',newCount,'Total de lançamentos registrados'],['Rematrículas',reCount,'Total de lançamentos registrados'],['Vagas disponíveis',t.vacancies,t.excess?`${t.excess} aluno(s) excedente(s) em outras turmas`:t.seats+' vagas de capacidade']])
    +`<div class="goal-strip"><div><span>Meta de alunos</span><strong>${t.goal?`${t.enrolled} <small>/ ${t.goal}</small>`:'Meta não definida'}</strong></div><div>${meter(t.goalPercent)}<small>${t.goal?`${formatPct(t.goalPercent)} realizado · ${t.missing?`faltam ${t.missing} alunos`:'meta alcançada'}`:'Defina uma meta para calcular o progresso automaticamente.'}</small></div>${btn('Gerenciar meta',"go('enrollments')",'alt small')}</div>`
    +`<div class="dashboard-grid">${card('Evolução das matrículas',chart)}${card('Ocupação por turma',S.classes.length?`<div class="card-summary"><strong>${t.seats?formatPct(t.occupancy):'—'}</strong><span>${t.enrolled} alunos / ${t.seats} lugares</span></div><div class="occupancy-list">${S.classes.slice().sort((a,b)=>occ(b)-occ(a)).map(x=>`<div class="occupancy-item"><div><b>${e(x.name)}</b><span>${n(x.students)} / ${n(x.capacity)} · ${formatPct(occ(x))}</span></div>${meter(occ(x),occ(x)>=90?'yellow':'')}</div>`).join('')}</div>`:emptyState('Nenhuma turma cadastrada','A ocupação será calculada a partir de turmas e matrículas.'),btn('Ver turmas',"go('classes')",'alt small'))}</div>`
    +`<div class="dashboard-third">${card('Execução orçamentária',S.budget.length?`<div class="finance-pair"><div><small>Realizado</small><strong>${money(t.actual)}</strong></div><div><small>Orçado</small><strong>${money(t.planned)}</strong></div></div>${meter(pct(t.actual,t.planned),'yellow')}<p class="row"><span>${t.remaining<0?'Acima do orçamento':'Saldo disponível'}</span><b class="${t.remaining<0?'text-danger':''}">${money(Math.abs(t.remaining))}</b></p><small>${t.planned?formatPct(pct(t.actual,t.planned))+' executado':'Sem valor orçado'}</small>`:emptyState('Orçamento ainda não informado','Cadastre contas e despesas para acompanhar a execução.'),btn('Abrir',"go('budget')",'alt small'))}${card('Inadimplência',`<div class="finance-pair"><div><small>Financeira</small><strong>${money(S.delinquency.financial)}</strong></div><div><small>Contábil</small><strong>${money(S.delinquency.accounting)}</strong></div></div><div class="row"><span>Dívida informada</span><b>${money(S.delinquency.debt)}</b></div><p class="hint">${n(S.delinquency.guardians)} responsáveis · ${n(S.delinquency.students)} alunos afetados. Indicadores informados manualmente${S.delinquency.updatedAt?' · atualização '+new Date(S.delinquency.updatedAt).toLocaleDateString('pt-BR'):''}.</p>`,btn('Abrir',"go('delinquency')",'alt small'))}</div>`
    +`<div class="dashboard-third">${card('Operação escolar',`<div class="stat-grid">${[['Solicitações abertas',S.requests.filter(x=>!['completed','rejected'].includes(x.status)).length],['Prazos vencidos',t.late],['Benefícios ativos',S.benefits.filter(x=>x.active).length],['Responsáveis cadastrados',(S.guardians||[]).length]].map(([label,value])=>`<div class="stat"><b>${value}</b><small>${label}</small></div>`).join('')}</div>`)}${card('Pontos de atenção',alerts.length?`<div class="attention-box">${alerts.map(x=>`<div class="attention-item"><i>!</i><span>${x}</span></div>`).join('')}</div>`:emptyState('Sem alertas nos dados informados','Os alertas consideram ocupação, prazos, orçamento e dívida.'))}</div>`;
}

function guardians(){const list=Array.isArray(S.guardians)?S.guardians:[];return head('Responsáveis','Cadastro de contatos reais. Não altera os indicadores agregados de inadimplência.',canEdit()?btn('+ Novo responsável','openGuardian()'):'')+metrics([['Cadastrados',list.length],['Com e-mail',list.filter(x=>x.email).length],['Com telefone',list.filter(x=>x.phone).length],['Com referência de aluno',list.filter(x=>x.student).length]])+table(['Nome / vínculo','Contato','Referência do aluno','Ações'],list.map(x=>`<tr><td><b>${e(x.name)}</b><br><small>${e(x.relationship)}</small></td><td>${e(x.email)||'—'}<br><small>${e(x.phone)}</small></td><td>${e(x.student)||'—'}</td><td>${canEdit()?btn('Editar',`openGuardian(${x.id})`,'alt small'):''}</td></tr>`).join(''),4,'Nenhum responsável cadastrado. Cadastre apenas contatos reais.');}
function openGuardian(guardianId){if(!canEdit('guardians'))return toast('Seu perfil não permite editar responsáveis.');const x=(S.guardians||[]).find(x=>x.id===guardianId)||{};modal(x.id?'Editar responsável':'Novo responsável',form([['name','Nome completo','text',null,x.name],['relationship','Vínculo com o aluno','text',null,x.relationship],['email','E-mail','email',null,x.email],['phone','Telefone','tel',null,x.phone],['student','Referência do aluno (opcional)','text',null,x.student]])+actions(`saveGuardian(${guardianId||'null'})`));}
function saveGuardian(guardianId){if(!canEdit('guardians'))return;const name=$('#f_name').value.trim();if(!name)return toast('Informe o nome.');const entry={name,relationship:$('#f_relationship').value.trim(),email:$('#f_email').value.trim(),phone:$('#f_phone').value.trim(),student:$('#f_student').value.trim()};if(!Array.isArray(S.guardians))S.guardians=[];const previous=S.guardians.find(x=>x.id===guardianId);if(previous)Object.assign(previous,entry);else S.guardians.push({id:id(),...entry});save();closeModal();render();toast('Responsável salvo.');}

let reportType='summary';
const reportNames={summary:'Resumo executivo',classes:'Turmas e vagas',enrollments:'Histórico de matrículas',budget:'Orçamento',benefits:'Benefícios',requests:'Solicitações',delinquency:'Inadimplência',guardians:'Responsáveis'};
function reportData(){const t=totals();switch(reportType){
  case 'classes':return {columns:['Turma','Capacidade','Alunos','Vagas disponíveis','Excedentes','Ocupação'],rows:S.classes.map(x=>[x.name,n(x.capacity),n(x.students),Math.max(0,n(x.capacity)-n(x.students)),Math.max(0,n(x.students)-n(x.capacity)),formatPct(occ(x))])};
  case 'enrollments':return {columns:['Data','Tipo','Turma','Quantidade','Responsável'],rows:S.enrollments.history.map(x=>[dateLabel(x.date),x.type==='re'?'Rematrícula':'Nova matrícula',S.classes.find(c=>String(c.id)===String(x.classId))?.name||x.className||'Turma não localizada',n(x.quantity),x.user])};
  case 'budget':return {columns:['Conta','Orçado (R$)','Realizado (R$)','Saldo (R$)'],rows:S.budget.map(x=>[x.category,n(x.budget),n(x.actual),n(x.budget)-n(x.actual)])};
  case 'benefits':return {columns:['Benefício','Tipo','Quantidade','Situação'],rows:S.benefits.map(x=>[x.name,x.type,n(x.quantity),x.active?'Ativo':'Inativo'])};
  case 'requests':return {columns:['Solicitação','Responsável','Prazo','Situação'],rows:S.requests.map(x=>[x.title,x.owner,dateLabel(x.due),labels[x.status]||x.status])};
  case 'delinquency':return {columns:['Indicador','Valor'],rows:[['Financeira (R$)',n(S.delinquency.financial)],['Contábil (R$)',n(S.delinquency.accounting)],['Dívida (R$)',n(S.delinquency.debt)],['Responsáveis',n(S.delinquency.guardians)],['Alunos',n(S.delinquency.students)]]};
  case 'guardians':return {columns:['Nome','Vínculo','E-mail','Telefone','Referência do aluno'],rows:(S.guardians||[]).map(x=>[x.name,x.relationship,x.email,x.phone,x.student])};
  default:return {columns:['Indicador','Valor'],rows:[['Alunos matriculados',t.enrolled],['Novas matrículas',n(S.enrollments.new)],['Rematrículas',n(S.enrollments.re)],['Capacidade',t.seats],['Vagas disponíveis',t.vacancies],['Excedentes',t.excess],['Meta',t.goal||'Não definida'],['Meta realizada',t.goal?formatPct(t.goalPercent):'—'],['Faltam para a meta',t.goal?t.missing:'—'],['Orçado (R$)',t.planned],['Realizado (R$)',t.actual],['Saldo orçamentário (R$)',t.remaining],['Dívida (R$)',n(S.delinquency.debt)],['Solicitações vencidas',t.late]]};
}}
function reports(){const data=reportData();return head('Relatórios','Dados atuais dos módulos · gerado em '+new Date().toLocaleString('pt-BR'),`<div class="head-actions">${btn('Exportar CSV','exportReport()','alt')}${btn('Imprimir','window.print()','alt')}${btn('Backup dos dados','exportBackup()','alt')}</div>`)+`<div class="report-control"><label for="reportType">Relatório</label><select id="reportType" onchange="reportType=this.value;render()">${Object.entries(reportNames).map(([value,label])=>`<option value="${value}" ${reportType===value?'selected':''}>${label}</option>`).join('')}</select><span>Atualizado automaticamente pelos cadastros</span></div><h2 class="print-title">${reportNames[reportType]}</h2>`+table(data.columns,data.rows.map(row=>'<tr>'+row.map(value=>`<td>${e(value??'—')}</td>`).join('')+'</tr>').join(''),data.columns.length,'Sem registros para este relatório.')+`<p class="hint">Os quantitativos atuais das turmas podem incluir saldos anteriores ao histórico de lançamentos. Valores financeiros são agregados e não representam conciliação bancária.</p>`;}
function downloadFile(content,name,type){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function exportReport(){const d=reportData(),query=($('#tableSearch')?.value||'').toLocaleLowerCase('pt-BR'),quote=x=>'"'+String(x??'').replace(/^[=+@\-\t\r]/,"'$&").replace(/"/g,'""')+'"';downloadFile('\uFEFF'+[d.columns,...d.rows.filter(row=>row.join(' ').toLocaleLowerCase('pt-BR').includes(query))].map(row=>row.map(quote).join(';')).join('\r\n'),`7e7-${reportType}-${localDate()}.csv`,'text/csv;charset=utf-8');toast('Relatório exportado.');}
function exportBackup(){downloadFile(JSON.stringify({exportedAt:new Date().toISOString(),storageKey:key,data:S},null,2),`7e7-backup-${localDate()}.json`,'application/json');}

function users(){return head('Usuários e permissões','Perfis existentes e permissões operacionais preservados.')+`<div class="notice">A aplicação é local e não possui autenticação. As permissões abaixo limitam a interface do primeiro perfil cadastrado; a segurança entre usuários exige servidor e login.</div>`+table(['Usuário','Perfil','Permissões'],S.users.map(x=>`<tr><td><b>${e(x.name)}</b></td><td>${e(x.role)}</td><td>${(Array.isArray(x.permissions)?x.permissions:[]).map(p=>`<span class="pill">${e(p)}</span>`).join(' ')||'Sem permissões atribuídas'}</td></tr>`).join(''),3,'Nenhum usuário cadastrado.');}

// Mantém as telas e os formulários originais, acrescentando indicadores e filtros.
const originalRender=render,originalModal=modal,originalClose=closeModal,originalEnrollmentSave=saveEnrollment;
const originalClasses=classes,originalBenefits=benefits,originalRequests=requests,originalBudget=budget;
classes=function(){const t=totals();return originalClasses().replace('<section class="card">',metrics([['Turmas',S.classes.length],['Alunos',t.enrolled],['Vagas disponíveis',t.vacancies],['Acima da capacidade',t.excess,'alunos excedentes']])+'<section class="card">');};
benefits=function(){return originalBenefits().replace('Edição, exclusão confirmada e indicadores preparados para atualização.','Benefícios cadastrados e quantidades informadas.').replace('<section class="card">',metrics([['Benefícios',S.benefits.length],['Ativos',S.benefits.filter(x=>x.active).length],['Quantidade ativa',S.benefits.filter(x=>x.active).reduce((a,x)=>a+n(x.quantity),0),'Pode incluir sobreposição entre benefícios'],['Inativos',S.benefits.filter(x=>!x.active).length]])+'<section class="card">');};
requests=function(){return originalRequests().replace('<section class="card">',metrics([['Solicitadas',S.requests.filter(x=>x.status==='requested').length],['Em andamento',S.requests.filter(x=>x.status==='doing').length],['Concluídas',S.requests.filter(x=>x.status==='completed').length],['Prazos vencidos',totals().late]])+'<section class="card">');};
budget=function(){const t=totals();return originalBudget().replace('Contas ilimitadas, despesas cumulativas e preparação para importação.','Contas e despesas acumuladas integradas ao painel e aos relatórios.').replace('<section class="card">',metrics([['Orçado',money(t.planned)],['Realizado',money(t.actual)],['Saldo',money(t.remaining)],['Execução',t.planned?formatPct(pct(t.actual,t.planned)):'—']])+'<section class="card">');};
let returnFocus=null;
modal=function(title,body){returnFocus=document.activeElement;originalModal(title,body);$('#modal h2').id='modalTitle';$('#modal').querySelectorAll('.field').forEach(field=>{const input=field.querySelector('input,select,textarea');if(input)field.querySelector('label').htmlFor=input.id;});$('#modal').querySelectorAll('input[type="number"]').forEach(input=>{input.min='0';input.step=['f_budget','f_value','f_financial','f_accounting','f_debt'].includes(input.id)?'0.01':'1';input.required=true;});$('#modal').querySelector('input,select,textarea,button')?.focus();};
closeModal=function(){originalClose();returnFocus?.focus();};
saveEnrollment=function(entryId){if(!canEdit('enrollments'))return toast('Seu perfil não permite editar matrículas.');if(!$('#f_date').value)return toast('Informe a data do lançamento.');const old=S.enrollments.history.find(x=>x.id===entryId);if(old){const room=S.classes.find(x=>String(x.id)===String(old.classId));if(!room||n(room.students)<n(old.quantity)||n(S.enrollments[old.type])<n(old.quantity))return toast('O saldo atual diverge do lançamento. Revise a turma antes de editar.');}originalEnrollmentSave(entryId);};
const originalRemoveEnrollment=removeEnrollment;
removeEnrollment=function(entryId){const entry=S.enrollments.history.find(x=>x.id===entryId);const room=S.classes.find(x=>String(x.id)===String(entry?.classId));if(entry&&(!room||n(room.students)<n(entry.quantity)||n(S.enrollments[entry.type])<n(entry.quantity)))return toast('Saldo insuficiente para estornar. Revise a turma antes de excluir.');originalRemoveEnrollment(entryId);};
function openImport(type){modal('Importar '+e(type),emptyState('Importação de planilhas em preparação','A versão anterior guardava somente o nome do arquivo. Os dados nunca foram processados. A importação será liberada com mapeamento de colunas, prévia e validação; utilize o cadastro manual por enquanto.')+`<div class="modal-actions">${btn('Fechar','closeModal()','alt')}</div>`);}

function openExpense(accountId){const account=S.budget.find(x=>x.id===accountId);if(!account)return;modal('Lançar despesa · '+e(account.category),form([['value','Valor da despesa','number',null,0],['expenseDate','Data','date',null,localDate()],['description','Descrição','text']])+actions(`saveExpense(${accountId})`));}
function saveExpense(accountId){if(!canEdit('budget'))return toast('Seu perfil não permite editar orçamento.');const account=S.budget.find(x=>x.id===accountId),value=Number($('#f_value').value),date=$('#f_expenseDate').value,description=$('#f_description').value.trim();if(!account||!Number.isFinite(value)||value<=0||!date||!description)return toast('Informe valor positivo, data e descrição.');if(!Array.isArray(account.expenses))account.expenses=[];account.expenses.push({id:id(),value,date,description,user:S.users[0]?.name||''});account.actual=Math.round((n(account.actual)+value)*100)/100;save();closeModal();render();toast('Despesa registrada; indicadores atualizados.');}
function viewExpenses(accountId){const account=S.budget.find(x=>x.id===accountId);if(!account)return;modal('Histórico · '+e(account.category),`<p class="hint">Realizado total: ${money(account.actual)}. Valores anteriores à criação do histórico permanecem no total, sem detalhamento inventado.</p><div class="list">${(account.expenses||[]).map(x=>`<div class="row"><div><b>${e(x.description)}</b><br><small>${dateLabel(x.date)} · ${e(x.user)}</small></div><b>${money(x.value)}</b></div>`).join('')||emptyState('Sem despesas detalhadas','Os próximos lançamentos terão data, descrição e responsável.')}</div><div class="modal-actions">${btn('Fechar','closeModal()','alt')}</div>`);}
function viewRequestHistory(requestId){const request=S.requests.find(x=>x.id===requestId);if(!request)return;modal('Histórico da solicitação',`<p><b>${e(request.title)}</b></p><p>${e(request.description)}</p><div class="list">${(request.history||[]).map(x=>`<div class="row"><span>${e(labels[x.status]||x.status)}</span><small>${e(new Date(x.date).toLocaleString('pt-BR'))}</small></div>`).join('')||emptyState('Sem alterações registradas','O histórico será atualizado nas próximas mudanças de status.')}</div><div class="modal-actions">${btn('Fechar','closeModal()','alt')}</div>`);}

function syncMenuState(){const mobile=typeof matchMedia==='function'&&matchMedia('(max-width: 680px)').matches;const closed=!$('aside').classList.contains('open');$('aside').inert=mobile&&closed;$('#menu').setAttribute('aria-expanded',String(!closed));}

function applyTableFilters(){const search=($('#tableSearch')?.value||'').toLocaleLowerCase('pt-BR'),status=$('#tableStatus')?.value||'',root=$('#page');
  // Em Matrículas, o primeiro quadro é a lista de turmas; o histórico é uma
  // tabela independente e não pode compor o total de registros encontrados.
  const primary=(page==='financial'&&breakEvenOpen?root.querySelector('#pe-turmas table tbody'):root.querySelector('table tbody'));
  const rows=(page==='enrollments'||(page==='financial'&&breakEvenOpen))?(primary?.querySelectorAll('tr')||[]):root.querySelectorAll('tbody tr');let visible=0;
  rows.forEach(row=>{if(row.querySelector('.empty'))return;const text=row.textContent.toLocaleLowerCase('pt-BR');row.hidden=!text.includes(search)||(status&&!Array.from(row.querySelectorAll('.pill')).some(p=>p.textContent===status));if(!row.hidden)visible++;});if($('#filterResult'))$('#filterResult').textContent=visible+' registro(s) encontrado(s)';}
render=function(){originalRender();syncMenuState();document.title=`${$('#page h1')?.textContent||'Gestão escolar'} · 7&7 CAJ`;$('#nav').querySelectorAll('button').forEach(button=>{button.setAttribute('aria-label',button.textContent);button.title=button.textContent;if(button.classList.contains('active'))button.setAttribute('aria-current','page');});$('#menu').setAttribute('aria-expanded','false');
  const profile=S.users[0];$('.profile b').textContent=profile?.name||'Perfil local';$('.profile small').textContent=profile?.role||'Gestão escolar';
  if(storageProblem)$('#page').insertAdjacentHTML('afterbegin','<div class="notice">Não foi possível ler os dados locais. A gravação está bloqueada para preservar o conteúdo existente.</div>');
  if(!canEdit()){ $('#page').querySelectorAll('button[onclick]').forEach(button=>{if(/open|remove/.test(button.getAttribute('onclick'))){button.disabled=true;button.title='Seu perfil não possui permissão para esta edição.';}});$('#page').insertAdjacentHTML('beforeend','<p class="hint">Consulta disponível. A edição deste módulo não está autorizada no perfil atual.</p>'); }
  if($('#page table')&&page!=='users'){const statuses=[...new Set(Array.from($('#page').querySelectorAll('tbody .pill')).map(p=>p.textContent))];const toolbar=document.createElement('div');toolbar.className='filter-toolbar';toolbar.innerHTML=`<label for="tableSearch">Buscar nos registros</label><input id="tableSearch" type="search" placeholder="Digite para filtrar…" oninput="applyTableFilters()">${statuses.length?`<select id="tableStatus" aria-label="Filtrar situação" onchange="applyTableFilters()"><option value="">Todas as situações</option>${statuses.map(s=>`<option>${e(s)}</option>`).join('')}</select>`:''}<span id="filterResult" role="status"></span>`;const first=$('#page .table-wrap').closest('section');first.before(toolbar);applyTableFilters();}
};
// Validação compartilhada antes dos manipuladores de gravação originais.
$('#modal').addEventListener('click',event=>{const button=event.target.closest('button');if(!button)return;const code=button.getAttribute('onclick')||'';if(!/save\(|saveEnrollment|saveGuardian|saveExpense/.test(code))return;if(!canEdit()){event.stopImmediatePropagation();event.preventDefault();toast('Seu perfil não permite esta alteração.');return;}for(const input of $('#modal').querySelectorAll('input')){if(!input.checkValidity()){event.stopImmediatePropagation();event.preventDefault();input.reportValidity();return;}}if(page==='delinquency')S.delinquency.updatedAt=new Date().toISOString();},true);
document.addEventListener('keydown',event=>{if(event.key==='Escape'){if($('#modalBg').classList.contains('open'))closeModal();$('aside').classList.remove('open');syncMenuState();}if(event.key==='Tab'&&$('#modalBg').classList.contains('open')){const items=Array.from($('#modal').querySelectorAll('button,input,select,textarea,[tabindex]')).filter(x=>!x.disabled);const first=items[0],last=items.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus();}}});
$('#menu').onclick=()=>{$('aside').classList.toggle('open');syncMenuState();};
window.addEventListener('resize',syncMenuState);
window.addEventListener('storage',event=>{if(event.key!==key)return;if($('#modalBg').classList.contains('open')){storageProblem=true;toast('Dados alterados em outra aba. Recarregue antes de salvar.');return;}try{S=normalizeState(JSON.parse(event.newValue));committedState=JSON.stringify(S);render();toast('Dados atualizados por outra aba.');}catch{storageProblem=true;render();}});
render();
