/* Read-only local candidate. Private records are fetched only after authorization. */
(function(){
  'use strict';
  const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const cash=x=>x==null?'Não demonstrado':(Number(x)/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
  function table(headers,rows){return `<div style="overflow:auto"><table><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${esc(c)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
  function renderModel(model){
    return `<div class="head"><div><h1>Ponto de Equilíbrio 2027</h1><p>${esc(model.presentationLabel||'Candidata local · não publicada')} · relatório confidencial</p></div><button class="btn alt" onclick="hideBreakEven()">Voltar</button></div><section class="card"><p>${esc(model.functionalAllocationNote)}</p><p>${esc(model.privacyNote)}</p><p>41 turmas · custo econômico ${cash(model.summary.soma41Centavos)} · reserva ${cash(model.summary.reservaCentavos)}</p><button class="btn" onclick="peAnalyticPDF()">RELATÓRIO GERAL PE 2027</button><button class="btn alt" onclick="showPESurplus()">SUPERÁVIT / DÉFICIT</button><p id="pePdfStatus" role="status"></p></section><section id="pe-turmas" class="card table-wrap" style="margin-top:16px;overflow:auto"><table><thead><tr><th>Turma</th><th>Capacidade</th><th>Custo total</th><th>Ticket líquido</th><th>PE</th><th>% capacidade</th><th>Margem</th><th>Status</th><th>Ações</th></tr></thead><tbody>${model.rows.map((r,i)=>`<tr data-analytic-class="${esc(r.id)}"><td>${esc(r.turma)}</td><td>${r.capacidade}</td><td>${cash(r.custoTotalCentavos)}</td><td>${cash(r.ticketLiquidoCentavosExato)}</td><td>${r.peCorrigido}</td><td>${Number(r.percentualCapacidade).toFixed(1)}%</td><td>${r.margemFisica}</td><td>${esc(r.status)}</td><td><button class="btn alt" onclick="peAnalyticDetails(${i})">Detalhes</button> <button class="btn alt" title="RELATÓRIO DETALHADO PDF" aria-label="RELATÓRIO DETALHADO PDF - ${esc(r.turma)}" onclick="peAnalyticPDF(${i})">PDF</button></td></tr>`).join('')}</tbody></table></section>`;
  }
  function renderDetails(r){return `<h2 id="modalTitle">${esc(r.turma)} — composição do PE</h2><p>${esc(r.status)}</p><p>${esc(r.functionalAllocationNote)}</p><p>Matriculados: ${r.matriculados}, somente informativo. Mensalidade: ${cash(r.tuitionCents)}.</p><p>${esc(r.revenue.basis)}</p>${table(['Receita por aluno','Valor'],[['Comercial/premissa',cash(r.revenue.premiseCents)],['Demais benefícios',cash(r.revenue.benefitCents)],['Após descontos',cash(r.revenue.afterDiscountCents)],['Inadimplência 4,5%',cash(r.revenue.delinquencyCents)],['Ticket líquido',cash(r.ticketLiquidoCentavosExato)]])}<h3>Benefícios previstos</h3>${table(['Tipo','%','Quantidade','Impacto no grupo'],r.benefitDetails.map(b=>[b.type,Number(b.rate)*100,b.quantity,cash(b.impactCents)]))}<h3>Docentes — parcelas da turma</h3>${table(['Professor','Disciplina','Aulas equivalentes','Semanal','Mensal'],r.teacherDetails.map(t=>[t.name,t.role,t.lessons,cash(t.weeklyCents),cash(t.monthlyCents)]))}${r.teacherBridgeCents?`<p>Ponte: ${cash(r.teacherBridgeCents)}. ${esc(r.teacherBridgeNote)}</p>`:''}<h3>Auxiliares/estagiárias</h3>${table(['Nome','Função','Parcela'],r.auxiliaryDetails.map(t=>[t.name,t.role,cash(t.allocatedCents)]))}<h3>Segmento</h3>${table(['Conta','Parcela','Critério'],r.segmentDetails.map(t=>[t.account,cash(t.allocatedCents),t.criterion]))}<h3>Global</h3>${table(['Conta','Parcela','Critério'],r.globalDetails.map(t=>[t.account,cash(t.allocatedCents),t.criterion]))}<h3>Custo total</h3>${table(['Componente','Valor'],r.components.map(c=>[c.label,cash(c.cents)]))}<p>Custo ${cash(r.custoTotalCentavos)} ÷ ticket ${cash(r.ticketLiquidoCentavosExato)} → PE ${r.peCorrigido}. Margem física: ${r.margemFisica}.</p><p>${esc(r.explanation)}</p><p>Saldo na capacidade máxima: ${cash(r.capacityBalanceCents)}.</p><button class="btn alt" onclick="document.getElementById('modalBg').classList.remove('open');document.getElementById('modalBg').style.display='none'">Fechar</button>`;}
  if(typeof module!=='undefined'&&module.exports){module.exports={renderModel,renderDetails};return;}
  // Server authorization protects the report on every host.
  const previousShow=showBreakEven,previousView=breakEvenView;
  let model=null,error='',loading=false,sequence=0;
  showBreakEven=async function(){
    if(Number(breakEvenYear)!==2027)return previousShow();
    const request=++sequence;page='financial';breakEvenOpen=true;loading=true;error='';model=null;render();
    try{const received=await api('break-even/analytic?year=2027');if(request===sequence)model=received;}
    catch(e){if(request===sequence)error=e.message;}
    finally{if(request===sequence){loading=false;if(breakEvenOpen)render();}}
  };
  breakEvenView=function(){return Number(breakEvenYear)!==2027?previousView():model?renderModel(model):`<section class="card"><h1>PE 2027 — composição validada</h1><p role="status">${loading?'Carregando composição…':esc(error||'Composição indisponível.')}</p><button class="btn" onclick="showBreakEven()">Atualizar</button><button class="btn alt" onclick="hideBreakEven()">Voltar</button></section>`;};
  window.peAnalyticDetails=function(index){if(model?.rows[index])window.peAnalyticDetailsRow(model.rows[index]);};
  window.peAnalyticDetailsRow=function(row){document.getElementById('modal').innerHTML=renderDetails(row);const bg=document.getElementById('modalBg');bg.style.display='flex';bg.classList.add('open');document.getElementById('modal').scrollTop=0;};
  window.peAnalyticPDF=async function(index){
    if(!model)return;
    const status=document.getElementById('pePdfStatus');status.textContent='Gerando relatório confidencial…';
    const query=new URLSearchParams({year:'2027',snapshot:model.snapshotSha256});if(index!==undefined){if(!model.rows[index])return;query.set('classId',model.rows[index].id);}
    try{const response=await fetch('/api/break-even/analytic.pdf?'+query,{credentials:'same-origin',cache:'no-store'});if(!response.ok){const body=await response.json();throw Error(body.error||'Não foi possível gerar o PDF.');}const url=URL.createObjectURL(await response.blob());const link=document.createElement('a');link.href=url;link.download='relatorio-pe-2027'+(index===undefined?'-geral':'-'+model.rows[index].id)+'.pdf';link.click();setTimeout(()=>URL.revokeObjectURL(url),30000);status.textContent='PDF gerado. Documento confidencial.';}catch(e){status.textContent=e.message;}
  };
})();
