/* Painel executivo utiliza exclusivamente o contrato autenticado do PE. */
var PEExecutive=(function(){
 'use strict';let current=[];
 const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const cash=x=>x==null?'Pendente':(x/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
 const segment=r=>r.name.includes('EM')?'EM':r.name.startsWith('G')?'EI':parseInt(r.name)<=5?'FI':'FII';
 function chart(title,items){const max=Math.max(1,...items.map(x=>Math.abs(x[1]??0)));const h=items.length*23+12;
 return `<section class="card"><h3>${esc(title)}</h3><svg role="img" aria-label="${esc(title)}" viewBox="0 0 600 ${h}" style="width:100%;min-width:300px">${items.map(([name,value],i)=>`<text x="0" y="${i*23+16}" font-size="12">${esc(name)}</text>${value==null?'':`<rect x="130" y="${i*23+3}" width="${Math.abs(value)/max*330}" height="15" fill="${value<0?'#a43139':'#063b76'}"/>`}<text x="475" y="${i*23+16}" font-size="11">${value==null?'Pendente':esc(value.toLocaleString('pt-BR',{maximumFractionDigits:2}))}</text>`).join('')}</svg></section>`;}
 function charts(rows){let known=rows.filter(r=>r.consideredCostCents!=null&&r.projectedRevenueCents!=null),sum=k=>known.reduce((a,r)=>a+(r[k]||0),0)/100;let components={};rows.forEach(r=>r.costs.forEach(c=>{let key=c.kind.split(' ')[0];components[key]=(components[key]||0)+c.cents/100;}));
 return chart('Matriculados × PE',rows.flatMap(r=>[[r.name+' matr.',r.enrolled],[r.name+' PE',r.pe]]))+chart('Receita × custo - mesmo universo (R$)',[['Receita',sum('projectedRevenueCents')],['Custo',sum('consideredCostCents')]])+chart('Ocupação (%)',rows.map(r=>[r.name,r.occupancyPercent]))+chart('Distância até o PE',rows.map(r=>[r.name,r.distanceToPE]))+chart('Composição de custos (R$)',Object.entries(components))+chart('Impacto dos descontos - ticket (R$)',rows.map(r=>[r.name,(r.averageFinancialDiscountCents??0)/100]));}
 function render(d){current=d.rows;const e=d.executive;if(!e)return '';
 const cards=[['Turmas / capacidade',e.classes+' / '+e.capacity],['Matriculados / ocupação',e.enrolled+' / '+(e.enrolled/e.capacity*100).toLocaleString('pt-BR',{maximumFractionDigits:2})+'%'],['PE conhecido (parcial)',e.peKnown+'; '+e.peMissing+' pendentes'],['Receita projetada (41)',cash(e.revenue)],['Custo alocado (37)',cash(e.cost)],['Resultado comparável ('+e.comparableClasses+')',cash(e.result)],['Acima / no / abaixo',e.above+' / '+e.at+' / '+e.below],['Superlotadas / auditoria',e.overcrowded+' / '+e.audit]];
 return `<section class="card"><h2>Dashboard executivo do PE 2027</h2><p role="status">${esc(d.structureNotice||'')}</p><a class="btn" href="/api/break-even/report.pdf">Gerar Relatório PE 2027</a><p>Premissas e custos parciais identificados. Resultado usa o mesmo universo de turmas; reserva R$ 15.827,05 separada. 1.016 benefícios: 902 com turma; 114 pendentes.</p><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:12px">${cards.map(([k,v])=>`<div class="card"><small>${esc(k)}</small><p><b>${esc(v)}</b></p></div>`).join('')}</div><div style="display:flex;gap:12px;flex-wrap:wrap"><label>Segmento <select id="pe-ex-segment" onchange="PEExecutive.filter()"><option value="">Todos</option>${['EI','FI','FII','EM'].map(s=>`<option>${s}</option>`).join('')}</select></label><label>Turma <select id="pe-ex-class" onchange="PEExecutive.filter()"><option value="">Todas</option>${d.rows.map(r=>`<option value="${esc(r.id)}">${esc(r.name)}</option>`).join('')}</select></label><label>Situação <select id="pe-ex-status" onchange="PEExecutive.filter()"><option value="">Todas</option><option value="above">Acima do PE</option><option value="below">Abaixo do PE</option><option value="full">Superlotada</option><option value="pending">Com pendência</option></select></label></div><p id="pe-ex-count">41 turmas selecionadas. Cards mostram o total da escola; gráficos e tabela seguem os filtros.</p><details><summary>Gráficos gerenciais</summary><div id="pe-ex-charts" style="display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:12px;overflow:auto">${charts(d.rows)}</div></details></section>`;}
 function matches(r,s,c,q){return (!s||segment(r)===s)&&(!c||r.id===c)&&(!q||q==='above'&&r.distanceToPE>0||q==='below'&&r.distanceToPE!=null&&r.distanceToPE<0||q==='full'&&r.vacancies<0||q==='pending'&&r.status!=='COMPROVADO');}
 function filter(){let s=document.getElementById('pe-ex-segment').value,c=document.getElementById('pe-ex-class').value,q=document.getElementById('pe-ex-status').value;const search=(document.getElementById('tableSearch')?.value||'').toLocaleLowerCase('pt-BR');const rows=current.filter(r=>matches(r,s,c,q)&&(!search||r.name.toLocaleLowerCase('pt-BR').includes(search)));const ids=new Set(rows.map(r=>r.id));document.querySelectorAll('[data-real-class]').forEach(el=>el.hidden=!ids.has(el.dataset.realClass));document.querySelectorAll('details[id^="real-"]').forEach(el=>el.hidden=!ids.has(el.id.slice(5)));document.getElementById('pe-ex-charts').innerHTML=charts(rows);document.getElementById('pe-ex-count').textContent=rows.length+' turmas selecionadas. Cards mostram o total da escola; gráficos e tabela seguem os filtros.';}
 return {render,filter,matches,segment,charts};
})();
if(typeof module!=='undefined')module.exports=PEExecutive;

if(typeof document!=='undefined'&&typeof applyTableFilters==='function'){const previousPEFilters=applyTableFilters;applyTableFilters=function(){previousPEFilters();if(document.getElementById('pe-ex-segment'))PEExecutive.filter();};}
