/* PE principal alimentado exclusivamente pela auditoria local autorizada. */
(function(){
  'use strict';
  const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const num=x=>x==null?'Pendente':esc(x);
  const cash=x=>x==null?'Pendente':(x/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
  const pct=x=>x==null?'Pendente':x.toFixed(2).replace('.',',')+'%';
  function renderReal(data){
    const s=data.summary;
    const executive=typeof PEExecutive!=='undefined'?PEExecutive.render(data):'';
    const rows=data.rows.map(r=>`<tr data-real-class="${esc(r.id)}"><th>${esc(r.name)}</th><td>${r.capacity}</td><td>${num(r.enrolled)}</td><td>${num(r.newStudents)}</td><td>${num(r.reenrolled)}</td><td>${num(r.vacancies)}</td><td>${pct(r.occupancyPercent)}</td><td>${cash(r.planningTuitionCents??r.tuitionCents)}</td><td>${cash(r.averageFinancialDiscountCents)}</td><td>${cash(r.plannedTicketCents??r.ticketCents)}</td><td>${cash(r.currentTicketCents)}</td><td>${num(r.plannedBenefitCount)}</td><td>${num(r.activeBenefitCount)}</td><td>${num(r.waitingBenefitCount)}</td><td>${cash(r.verifiedCostCents)}</td><td><b>${num(r.pe)}</b><br><small>${esc(r.status)}</small></td><td>${num(r.distanceToPE)}</td><td>${esc(r.enrollmentSituation||'PE pendente')}</td><td>${cash(r.projectedRevenueCents)}</td><td>${cash(r.currentRevenueCents)}</td><td>${cash(r.projectedResultCents)}</td><td><a href="#real-${esc(r.id)}">Ver memória de cálculo</a></td></tr>`).join('');
    const memories=data.rows.map(r=>`<details id="real-${esc(r.id)}"><summary>${esc(r.name)} — Ver memória de cálculo</summary><p>${esc(r.note)}</p><h3>Receita individual agregada</h3><p>Mensalidade oficial: ${cash(r.tuitionCents)} (orçamento 2027, p. 2). Alunos válidos/encontrados: ${r.acceptedStudentCount}/${r.sourceStudentCount}. Bruta: ${cash(r.grossCents)}; descontos: ${cash(r.discountCents)}; pós-desconto: ${cash(r.postDiscountCents)}; inadimplência 4,5%: ${cash(r.delinquencyCents)}; líquida: ${cash(r.netRevenueCents)}; ticket: ${cash(r.ticketCents)}.</p><ul>${Object.entries(r.benefits).map(([k,v])=>`<li>${esc(k)}: ${v.count} registros; ${cash(v.discountCents)}. Todos os Descontos, linhas ${v.sourceRows.join(', ')}.</li>`).join('')}</ul><p>Exceções: ${r.issues.length?esc(r.issues.map(i=>'linha '+i.row+': '+i.issues.join(', ')).join('; ')):'Nenhuma nos registros encontrados. Ausência de base não significa receita zero.'}</p><h3>Custo</h3><ul>${r.costs.map(c=>`<li>${esc(c.kind)}: ${cash(c.cents)} — ${esc(c.evidence)}</li>`).join('')}</ul><p>Outros diretos, encargos adicionais e despesas operacionais: pendentes de composição. Nenhum encargo foi somado novamente. Exposição pendente:</p><ul>${r.pendingCosts.map(c=>`<li>${esc(c.kind)}: ${cash(c.cents)}</li>`).join('')}${r.unknownCosts.map(c=>`<li>${esc(c.person)}: valor desconhecido.</li>`).join('')}</ul><h3>PE real</h3><p>${r.planningAssumption?'Teto(custo reconciliado ÷ ticket exato da premissa):':'Teto(custo parcial × alunos válidos ÷ receita líquida):'} ${num(r.pe)}. APE parcial = custo ÷ (mensalidade × 0,955): ${r.ape==null?'Pendente':r.ape.toFixed(4)}. PCLD neutralizada no PE para evitar dupla incidência com inadimplência. PCLD adicionada: R$ 0,00; desconto estrutural adicional: 0%.</p><p>Cobertura do envelope de custo conhecido: ${pct(r.costCoveragePercent)}; cobertura financeira dos registros: ${pct(r.revenueCoveragePercent)}. Confiança do PE: Pendente. ${esc(r.confidenceReason)}</p><details><summary>Referências históricas de auditoria</summary><p>PE documental impresso: ${num(r.historicalDocumentaryPE)}. Cenário provisório anterior: ${num(r.historicalProvisionalPE)}. Não são o PE real.</p></details></details>`).join('');
    const enroll=data.enrollmentSummary;
    return `<div class="head"><div><h1>PE REAL 2027</h1><p>Orçamento reconciliado · descontos individuais · matrículas atuais</p></div><button class="btn alt" onclick="hideBreakEven()">Voltar</button></div><section class="card"><p><b>${s.classes} turmas · ${s.capacity} vagas.</b> ${s.confirmed} PEs completos comprovados; ${s.partial} estimativas parciais; ${s.audit} em auditoria.</p>${enroll?`<p><b>${enroll.enrolled} matriculados · ${enroll.new} novos · ${enroll.re} rematrículas · saldo líquido ${enroll.vacancies} vagas.</b> Vagas negativas preservam superlotação.</p>`:''}<p>PE REAL 2027 é o planejamento em alunos pelo ticket previsto. Usa o valor financeiro do orçamento e o mix validado da planilha; mix previsto confirmado pelo financeiro; composição nominal dos custos ainda não encerrada. G2 A/B usam premissa exclusiva de 12% para ingressantes 2027 enquanto não houver mix individual; o mix cadastrado substitui a premissa, sem acumulação.</p><p>Custos documentais com destino identificado: ${cash(s.verifiedCostCents)}. Custo com destino pendente: ${cash(s.pendingCostCents)}, além de valores adicionais ainda não determinados. Descontos orçados substituídos: R$ 177.901,08. Nenhuma inviabilidade definitiva certificada.</p><p>${s.validRecords} benefícios associados às turmas; ${s.rejectedRecords} preservados com vínculo de turma pendente. 1.016 benefícios e 775 matrículas são populações diferentes por regra confirmada, sem divergência. Receita projetada aplica o mix previsto à quantidade atual; receita atual vinculada usa apenas matrículas nominais. Benefício previsto não é matrícula. Matrículas não alteram o custo ou a fórmula do PE.</p></section>${executive}<section class="card" style="margin-top:16px"><div id="pe-turmas" class="table-wrap" style="overflow:auto" role="region" tabindex="0" aria-label="PE real das 41 turmas"><table><thead><tr>${['Turma','Capacidade','Matriculados','Novos','Rematrículas','Vagas','Ocupação','Mensalidade','Desconto médio financeiro','Ticket previsto líquido','Ticket atual matriculado','Benefícios previstos','Ativos','Aguardando matrícula','Custo orçado reconciliado','PE real calculado','Matriculados − PE','Situação (estimativa)','Receita projetada pelo mix previsto','Receita atual vinculada','Resultado projetado','Memória'].map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows}</tbody></table></div></section><section class="card" style="margin-top:16px"><h2>Conciliação de benefícios</h2><p>Marcando Vidas: 45% uma única vez. Bolsa filantrópica: 50%. Concessão composta de 95% somente no registro com percentual individual e cobrança corroborados, uma única vez. Descontos individuais substituem os 3% e as estimativas 4126005/4126007. Inadimplência aplicada uma vez; PCLD fora do custo. Isso não é conciliação nominal por evento, que permanece pendente. Referências antigas ficam somente nas memórias.</p><h2>Memórias de cálculo</h2>${memories}</section>`;
  }
  if(typeof module!=='undefined'&&module.exports){module.exports={renderReal};return;}
  const oldShow=showBreakEven,oldView=breakEvenView,oldIntegrated=openIntegratedTeachingFinance;
  let snapshot=null,error='',loading=false,sequence=0;
  showBreakEven=async function(){
    if(Number(breakEvenYear)!==2027)return oldShow();
    const request=++sequence;page='financial';breakEvenOpen=true;snapshot=null;error='';loading=true;render();
    try{const data=await api('break-even/real?year=2027');if(request!==sequence)return;
      if(data.contractVersion!=='pe-real-2027-v1'||data.rows.length!==41)throw new Error('Base de auditoria incompatível');snapshot=data;
    }catch(e){if(request===sequence)error=e.message||'Falha na auditoria local';}
    finally{if(request===sequence){loading=false;if(breakEvenOpen)render();}}
  };
  breakEvenView=function(){
    if(Number(breakEvenYear)!==2027)return oldView();
    return snapshot?renderReal(snapshot):`<section class="card"><h1>PE REAL 2027</h1><p role="status">${loading?'Carregando auditoria local…':esc(error||'Base ainda não carregada.')}</p><button class="btn" onclick="showBreakEven()">Atualizar</button><button class="btn alt" onclick="hideBreakEven()">Voltar</button></section>`;
  };
  openIntegratedTeachingFinance=async function(){if(Number(breakEvenYear)===2027)return showBreakEven();return oldIntegrated();};
})();
