/* Camada de operação compartilhada sobre a aplicação existente. */
'use strict';
const M=SchoolModel;
const App={mode:'connecting',user:null,csrf:null,version:0,busy:false,remotePending:false,events:null,health:null,legacy:M.clone(S),preview:null};
S=M.recalculate(M.migrate(S));
const currentUser=()=>App.user;
const can=(module,action='view')=>M.permitted(currentUser(),module,action);
canEdit=function(module=page){return can(module,'edit')||can(module,'create');};
const canEditEnrollmentQuantities=()=>can('enrollments','edit');
const uid=M.cryptoId,jsid=x=>e(JSON.stringify(String(x))),findBy=(list,value)=>list.find(x=>String(x.id)===String(value));
const val=name=>$('#f_'+name)?.value?.trim()||'',numval=name=>Number(val(name));
const optionalPercent=x=>x==null?'Não informado':formatPct(Number(x));
function allowedButton(module,action,label,code,style='alt small'){return can(module,action)?btn(label,code,style):'';}
async function api(path,body,binary=false){const response=await fetch('/api/'+path,{method:body?'POST':'GET',cache:'no-store',headers:body?{'Content-Type':'application/json','X-CSRF-Token':App.csrf||''}:{},body:body?JSON.stringify(body):undefined,credentials:'same-origin'});if(!response.ok){let problem;try{problem=await response.json();}catch{problem={error:'Servidor indisponível.'};}if(response.status===401)showLogin();const error=Error(problem.error||'Não foi possível concluir.');error.httpStatus=response.status;error.responseBody=problem;error.endpoint='/api/'+path;throw error;}return binary?response.blob():response.json();}
async function refreshShared(){const snapshot=await api('state');S=M.migrate(snapshot.state);App.version=snapshot.version;App.user=snapshot.user;App.remotePending=false;render();}
async function commit(module,action,update,message='Alteração salva.',confirmation){
  if(App.mode!=='shared')return toast('Conecte-se à base compartilhada antes de alterar dados.');if(!can(module,action))return toast('Seu perfil não permite esta ação.');if(App.busy)return;if(App.remotePending)return toast('Há alterações de outra sessão. Feche o formulário e abra novamente para revisar os dados.');
  const before=M.clone(S),next=M.clone(S);let requestPayload=null;try{update(next);M.validate(next,before);M.recalculate(next);App.busy=true;
    requestPayload={changes:M.changes(before,next),version:App.version,module,action,confirmation};const result=await api('state',requestPayload);S=M.migrate(result.state);App.version=result.version;
    closeModal();render();toast(message);
  }catch(error){toast(module==='financial'?`Não foi possível salvar: ${error.message}.`:error.message);if(App.mode==='shared'&&/outra sessão|atualizados/.test(error.message))App.remotePending=true;}finally{App.busy=false;}
}
persistState=function(){throw Error('Use as ações integradas para salvar com validação e auditoria.');};
function connectionLabel(){return App.mode==='shared'?'Base compartilhada · atualização ao vivo':'Base compartilhada necessária';}
function startEvents(){App.events?.close();App.events=new EventSource('/api/events');App.events.addEventListener('changed',async event=>{const {version}=JSON.parse(event.data);if(version===App.version||App.busy)return;if($('#modalBg').classList.contains('open')){App.remotePending=true;toast('Alteração recebida de outra sessão. O formulário foi preservado; feche para atualizar.');}else try{await refreshShared();}catch(error){toast(error.message);}});App.events.addEventListener('revoked',()=>{App.events.close();App.user=null;S=M.migrate({});showLogin('Sessão encerrada ou permissões alteradas. Entre novamente.');});}
function showLogin(note=''){page='login';$('#nav').innerHTML='';$('#page').innerHTML=head('Acesso à Gestão Escolar','Base compartilhada do Colégio Adventista de Juazeiro')+card('Entrar',`<p class="hint">${e(note||'Use o usuário cadastrado pelo administrador.')}</p>${form([['email','E-mail','email'],['password','Senha','password']])}<div class="modal-actions">${btn('Entrar','login()')}</div>`)+(!App.health?.configured?'<div class="notice">Nenhum administrador configurado. No computador do servidor, execute <code>python server.py --create-admin</code> e informe seus dados reais. Depois inicie <code>python server.py</code>.</div>':'');$('.profile b').textContent='Acesso restrito';$('.profile small').textContent='Autenticação necessária';}
function showSharedRequired(note='Inicie ou acesse o servidor compartilhado para consultar e alterar os dados escolares.') {App.events?.close();App.mode='unavailable';App.user=null;page='unavailable';$('#nav').innerHTML='';$('#page').innerHTML=head('Base compartilhada necessária','Os dados escolares não são abertos nem gravados em cópias locais.')+card('Conexão necessária',`<p class="hint">${e(note)}</p><p class="hint">Acesse o mesmo endereço do servidor usado pelos demais usuários. O arquivo <code>index.html</code> não deve ser aberto diretamente.</p>`);$('.profile b').textContent='Sem conexão';$('.profile small').textContent='Base compartilhada necessária';}
async function login(){try{const result=await api('login',{email:val('email'),password:$('#f_password')?.value||''});App.user=result.user;App.csrf=result.csrf;App.mode='shared';await refreshShared();page=can('dashboard')?'dashboard':'enrollments';render();startEvents();}catch(error){const hint=$('#page .hint');if(hint){hint.textContent=error.message;hint.setAttribute('role','alert');}toast(error.message);}}
async function logout(){try{await api('logout',{});}finally{App.events?.close();App.user=null;S=M.migrate({});showLogin();}}
async function bootstrapShared(){showSharedRequired('Conectando à base compartilhada…');if(location.protocol==='file:'){showSharedRequired('Abra o sistema pelo endereço do servidor compartilhado; não use o arquivo HTML diretamente.');return;}try{const health=await fetch('/api/health',{cache:'no-store'});if(!health.ok)throw Error('Servidor indisponível.');App.health=await health.json();if(!App.health.available)throw Error('Base compartilhada indisponível.');App.mode='shared';try{const me=await api('me');App.user=me.user;App.csrf=me.csrf;await refreshShared();startEvents();}catch{showLogin();}}catch(error){showSharedRequired(error.message||'Não foi possível conectar à base compartilhada.');}}
go=function(target){if(App.mode!=='shared'){showSharedRequired();return;}page=target;refreshShared().catch(error=>toast(error.message));};
async function refreshCurrentPage(){if(App.mode!=='shared')return showSharedRequired();try{await refreshShared();toast('Dados atualizados a partir da base compartilhada.');}catch(error){toast(error.message);}}

function statsOf(c){return M.classStats(S,c);}
totals=function(){const t=M.totals(S),planned=S.budget.reduce((a,x)=>a+n(x.budget),0),actual=S.budget.reduce((a,x)=>a+n(x.actual),0);return {...t,enrolled:t.total,seats:t.capacity,occupancy:t.capacity?t.total/t.capacity*100:0,planned,actual,remaining:planned-actual,goalPercent:t.percent,late:S.requests.filter(x=>x.due&&x.due<localDate()&&!['completed','rejected'].includes(x.status)).length};};
function reconciliationNotice(){const t=M.totals(S);return t.unclassified||t.unallocated?`<div class="notice"><b>Conferência dos saldos anteriores</b><p>${t.unclassified} aluno(s) no saldo legado sem divisão entre novos e rematrículas; ${t.unallocated} lançamento(s) globais sem turma vinculada. Os dados originais foram preservados. O total oficial considera apenas novos + rematrículas identificados.</p></div>`:'';}
function enrollmentMetrics(){const t=M.totals(S);return metrics([['Total matriculados',t.total,'Rematrículas + alunos novos'],['Alunos novos',t.new],['Rematrículas',t.re],['Vagas disponíveis',t.vacancies]])+`<div class="goal-strip"><div><span>Meta de matrículas</span><strong>${t.goal.toLocaleString('pt-BR')} alunos</strong></div><div>${meter(t.percent)}<small>${formatPct(t.percent)} alcançado · faltam ${t.missing}${t.excessGoal?' · '+t.excessGoal+' acima da meta':''}</small></div></div>`;}
function classStatus(c){const x=statsOf(c);return x.status==='above'?['above','Acima da capacidade']:x.status==='full'?['full','Lotada']:x.status==='attention'?['attention','Próxima da capacidade']:['normal','Dentro da capacidade'];}
const educationStages=['Educação Infantil','Fundamental Anos Iniciais','Fundamental Anos Finais','Ensino Médio'];
let classQuery='',classStage='all';
function filteredClasses(){const query=M.fold(classQuery);return S.classes.filter(c=>(classStage==='all'||c.stage===classStage)&&(!query||M.fold(c.name).includes(query)));}
function classFilter(){return `<div class="filter-toolbar"><label for="classStage">Etapa</label><select id="classStage" onchange="classStage=this.value;render()"><option value="all">Todas as turmas</option>${educationStages.map(stage=>`<option value="${e(stage)}" ${stage===classStage?'selected':''}>${e(stage)}</option>`).join('')}</select><label for="classSearch">Buscar turma</label><input id="classSearch" type="search" value="${e(classQuery)}" placeholder="Ex.: 7º A" oninput="classQuery=this.value;render()"><span>${filteredClasses().length} de ${S.classes.length} turma(s)</span></div>`;}
function classTable(edit=false){return table([...(edit?['Ações']:[]),'Turma','Etapa','Capacidade','Rematrículas','Alunos novos','Total matriculados','Vagas disponíveis','Ocupação','Situação'],filteredClasses().map(c=>{const x=statsOf(c),[tone,label]=classStatus(c),capacity=x.capacity||'Não informada',actions=`${allowedButton('classes','edit','✎ Editar',`openClass(${jsid(c.id)})`)} ${canEditEnrollmentQuantities()?btn('Editar quantitativos',`openOpening(${jsid(c.id)})`,'alt small'):''} ${allowedButton('classes','delete','⌫ Excluir',`deleteClass(${jsid(c.id)})`,'danger small')}`;return `<tr>${edit?`<td class="class-actions-cell"><div class="class-actions">${actions}</div></td>`:''}<td><b>${e(c.name)}</b>${c.template?'<br><small>Dados ainda não informados</small>':''}${x.unclassified?`<br><small>${x.unclassified} matriculado(s) ainda não classificado(s)</small>`:''}</td><td><small>${e(c.stage||'Não classificada')}</small></td><td>${capacity}</td><td>${x.re}</td><td>${x.new}</td><td><b>${x.total}</b></td><td>${x.vacancies}${x.excess?`<br><strong class="text-danger">Excedente: ${x.excess} alunos</strong>`:''}</td><td>${x.occupancy==null?'Sem capacidade':formatPct(x.occupancy)}${meter(x.occupancy??100,tone==='normal'?'':'yellow')}</td><td><span class="pill ${tone}">${label}</span>${x.excess?'<p class="text-danger">A turma ultrapassou a capacidade.</p>':''}</td></tr>`;}).join(''),edit?10:9,'Nenhuma turma corresponde à busca.');}
let financeYear=2027,financeSegment='all',financeClass='all';
const financialAllowed=(action='view')=>can('financial',action);
function selectedFinancialYear(){return M.financialYear(S,financeYear)||M.financialYear(S,S.activeAcademicYear);}
function financeRows(){return S.classes.filter(c=>(financeSegment==='all'||M.segmentForClass(c)===financeSegment)&&(financeClass==='all'||String(c.id)===String(financeClass))).map(c=>M.financialStats(S,c,financeYear));}
function financeControls(){const years=(S.academicYears||[]).map(y=>`<option value="${y.year}" ${Number(financeYear)===y.year?'selected':''}>${y.year}</option>`).join('');return `<div class="filter-toolbar"><label>Ano letivo</label><select onchange="financeYear=Number(this.value);render()">${years}</select><label>Segmento</label><select onchange="financeSegment=this.value;render()"><option value="all">Todos</option>${M.FINANCIAL_SEGMENTS.map(([id,label])=>`<option value="${id}" ${financeSegment===id?'selected':''}>${e(label)}</option>`).join('')}</select><label>Turma</label><select onchange="financeClass=this.value;render()"><option value="all">Todas</option>${S.classes.map(c=>`<option value="${e(c.id)}" ${String(financeClass)===String(c.id)?'selected':''}>${e(c.name)}</option>`).join('')}</select></div>`;}
function financialSummary(){const rows=financeRows(),t=M.financialTotals(S,financeYear,rows.map(x=>S.classes.find(c=>c.id===x.id)||{}));return metrics([['Receita bruta potencial',t.potential==null?'Não informada':money(t.potential)],['Descontos concedidos',money(t.discounts)],['Receita líquida conhecida',money(t.net)],['Ticket médio líquido',money(t.ticket)]])+`<div class="stat-grid"><div class="stat"><b>${formatPct(t.averageDiscount)}</b><small>Desconto médio efetivo</small></div><div class="stat"><b>${t.fullExempt}</b><small>Bolsas 100%</small></div><div class="stat"><b>${t.partial}</b><small>Descontos parciais</small></div><div class="stat"><b>${t.unclassifiedFinancial}</b><small>Não classificados</small></div></div>`;}
function financialTable(){const rows=financeRows();return table(['Turma','Segmento','Matriculados','Classificados','Não classificados','Mensalidade','Receita líquida conhecida','Ações'],rows.map(x=>`<tr><td><b>${e(x.name)}</b></td><td>${e(x.segmentLabel)}</td><td>${x.total}</td><td>${x.classified}</td><td>${x.unclassifiedFinancial}</td><td>${x.tuition==null?'Não informada':money(x.tuition)}</td><td>${money(x.net)}</td><td>${financialAllowed('edit')&&Number(financeYear)===Number(S.academicDataYear)?btn('Bolsas e descontos',`openFinancialClass(${jsid(x.id)})`,'alt small'):''}</td></tr>`).join(''),8,'Não há dados acadêmicos para este filtro.');}
function financial(){const y=selectedFinancialYear(),actions=`<div class="head-actions">${btn('Ponto de equilíbrio 2027','showBreakEven()','alt')}${financialAllowed('edit')?btn('Receita 2027','openRevenue2027()','alt')+btn('Importar descontos e benefícios','openFinancialImport()','alt')+btn('Parâmetros do ano','openFinancialParameters()','alt')+btn('+ Ano letivo','openAcademicYear()','alt'):''}</div>`;return head('Parâmetros Financeiros do Ano Letivo','Receitas e classificações financeiras por turma. O ponto de equilíbrio usa uma camada orçamentária separada e auditável.',actions)+financeControls()+financialSummary()+card('Receita por turma',Number(financeYear)!==Number(S.academicDataYear)?`<div class="notice">Ainda não há quantitativos acadêmicos vinculados a ${financeYear}. Os parâmetros podem ser configurados sem alterar os dados históricos de ${S.academicDataYear}.</div>`:financialTable())+financialImportHistory()+revenue2027Panel();}
function openAcademicYear(){if(!financialAllowed('edit'))return;modal('Novo ano letivo',form([['year','Ano letivo','number',null,Math.max(...S.academicYears.map(x=>x.year))+1]])+actions('saveAcademicYear()'));}
function saveAcademicYear(){const year=numval('year');commit('financial','edit',s=>{if(!M.integer(year)||s.academicYears.some(x=>x.year===year))throw Error('Informe um novo ano letivo válido.');s.academicYears.push(M.defaultFinancialYear(year,false));s.activeAcademicYear=year;financeYear=year;},'Ano letivo criado sem alterar dados históricos.');}
function openFinancialParameters(){const y=selectedFinancialYear();if(!y||!financialAllowed('edit'))return;modal('Parâmetros financeiros · '+y.year,`<p class="hint">Mensalidades são configuradas por segmento e ano letivo. Campos vazios permanecem não informados.</p>`+form(y.parameters.map(p=>['tuition_'+p.id,p.label,'number',null,p.tuition??'']))+actions('saveFinancialParameters()'));}
function saveFinancialParameters(){commit('financial','edit',s=>{const y=M.financialYear(s,financeYear);for(const p of y.parameters){const raw=val('tuition_'+p.id);p.tuition=raw===''?null:numval('tuition_'+p.id);}},'Parâmetros financeiros do ano atualizados.');}
function financeVariableRow(item={}){return `<div class="row finance-variable"><input data-finance-percent type="number" min="0" max="100" value="${e(item.percent??0)}" aria-label="Percentual de desconto"><span>% de desconto</span><input data-finance-quantity type="number" min="0" value="${e(item.quantity??0)}" aria-label="Quantidade de alunos"><button class="btn alt small" type="button" onclick="this.parentElement.remove()">Remover</button></div>`;}
function addFinanceVariable(){const host=$('#financeVariables');if(host)host.insertAdjacentHTML('beforeend',financeVariableRow());}
function openFinancialClass(classId){if(!financialAllowed('edit'))return;const c=findBy(S.classes,classId),data=M.classificationFor(S,c,financeYear);if(!c)return;modal('Bolsas, Benefícios e Descontos · '+e(c.name),`<p class="hint">Matriculados: ${M.classStats(S,c).total}. A soma das classificações não pode ultrapassar esse total. Alunos restantes ficam como não classificados financeiramente.</p>`+form(M.FINANCIAL_CATEGORIES.map(([id,label,percent])=>['finance_'+id,`${label} — ${percent}%`,'number',null,data.fixed[id]??0]))+`<h3>Outros descontos variáveis</h3><div id="financeVariables">${data.variables.map(financeVariableRow).join('')}</div>${btn('+ Adicionar faixa','addFinanceVariable()','alt small')}<div class="modal-actions">${btn('Cancelar','closeModal()','alt')}${btn('Salvar',`saveFinancialClass(${jsid(classId)})`)}</div>`);}
function saveFinancialClass(classId){commit('financial','edit',s=>{const c=findBy(s.classes,classId),y=M.financialYear(s,financeYear),fixed={};for(const [id] of M.FINANCIAL_CATEGORIES){const quantity=numval('finance_'+id);if(!M.integer(quantity))throw Error('As quantidades devem ser números inteiros não negativos.');fixed[id]=quantity;}const variables=Array.from($('#financeVariables').querySelectorAll('.finance-variable')).map((row,index)=>({id:row.dataset.variableId||'variable-'+Date.now()+'-'+index,percent:Number(row.querySelector('[data-finance-percent]').value),quantity:Number(row.querySelector('[data-finance-quantity]').value)}));if(variables.some(x=>!M.integer(x.quantity)||!Number.isFinite(x.percent)||x.percent<0||x.percent>100))throw Error('Cada desconto variável deve ter percentual entre 0% e 100% e quantidade inteira não negativa.');const activeVariables=variables.filter(x=>x.quantity>0),classified=Object.values(fixed).reduce((sum,quantity)=>sum+quantity,0)+activeVariables.reduce((sum,item)=>sum+item.quantity,0),matriculated=M.classStats(s,c).total;if(classified>matriculated)throw Error(`Classificados: ${classified}. A turma possui ${matriculated} matriculado(s).`);y.classifications[c.id]={fixed,variables:activeVariables};},'Classificação financeira salva; projeção recalculada.');}
function financialImportHistory(){const records=(S.imports||[]).filter(item=>item.kind==='financial_classifications').slice().reverse();return card('Histórico de importações de descontos e benefícios',table(['Arquivo','Ano','Data/hora','Itens aplicados','Pendentes','Duplicados','Aprovado por'],records.map(item=>`<tr><td>${e(item.name)}</td><td>${e(item.year)}</td><td>${e(new Date(item.date).toLocaleString('pt-BR'))}</td><td>${item.count}</td><td>${item.pending}</td><td>${item.duplicates}</td><td>${e(item.approvedBy||'—')}</td></tr>`).join(''),7,'Nenhuma importação financeira aprovada.'))}
function openFinancialImport(){if(!financialAllowed('edit'))return;if(App.mode!=='shared')return modal('Importação segura',emptyState('Requer o servidor local','A prévia e a aprovação administrativa são realizadas no servidor compartilhado.')+`<div class="modal-actions">${btn('Fechar','closeModal()','alt')}</div>`);modal('Importar descontos e benefícios',`<p class="hint">Priorize Excel ou CSV. PDF é aceito somente quando a tabela textual puder ser lida com segurança. Nenhuma classificação será aplicada antes da prévia, das decisões e da aprovação administrativa.</p><div class="form-row"><label>Arquivo<input id="financialImportFile" type="file" accept=".xlsx,.csv,.pdf"></label></div><p class="hint">Colunas aceitas: Turma, Benefício/Tipo, Percentual, Quantidade. Campo Aluno/Nome do aluno torna o item pendente, pois este módulo é quantitativo.</p><div class="modal-actions">${btn('Cancelar','closeModal()','alt')}${btn('Gerar prévia',`previewFinancialImport()`)}</div>`);}
function financialCategoryOptions(value){const options=[['Sem desconto',0],['Bolsa filantrópica',100],['Bolsa filantrópica',50],['Filho de funcionário',100],['Filho de funcionário',80],['Filho de obreiro',100],['Projeto Marcando Vidas',45],['Desconto variável','']];return `<select data-financial-category>${options.map(([label,percent])=>`<option value="${e(label)}" ${M.fold(label)===M.fold(value)?'selected':''}>${e(label)}${percent===''?'':` — ${percent}%`}</option>`).join('')}</select>`;}
async function previewFinancialImport(){const file=$('#financialImportFile')?.files[0];if(!file)return toast('Selecione o arquivo.');if(file.size>10*1024*1024)return toast('Limite de 10 MB por arquivo.');try{const p=await api('financial-classifications/preview',{name:file.name,content:await asBase64(file),year:financeYear});App.financialImportPreview=p;const rows=p.rows.map((item,index)=>`<tr><td>${item.line}</td><td><select data-financial-class><option value="">Turma pendente</option>${S.classes.map(room=>`<option value="${e(room.id)}" ${String(room.id)===String(item.classId)?'selected':''}>${e(room.name)}</option>`).join('')}</select></td><td>${financialCategoryOptions(item.category)}</td><td><input data-financial-percent type="number" min="0" max="100" value="${e(item.percent??'')}"></td><td><input data-financial-quantity type="number" min="0" step="1" value="${e(item.quantity??'')}"></td><td><select data-financial-action><option value="accept" ${item.status==='ready'?'selected':''}>Aceitar</option><option value="edit" ${item.status==='ready'?'':'selected'}>Editar</option><option value="ignore">Ignorar</option></select></td><td><input data-financial-reason placeholder="Obrigatória ao editar/ignorar"></td><td>${e(item.reason||item.status)}</td></tr>`).join('');modal('Prévia de descontos e benefícios',`<p><b>${e(p.name)}</b> · ano ${p.year} · ${p.rows.length} item(ns) · ${p.pending} pendente(s) · ${p.duplicates} duplicidade(s). Itens pendentes não serão aplicados sem correção explícita.</p>`+table(['Linha','Turma','Tipo','%','Quantidade','Decisão','Justificativa','Validação'],rows,8,'Sem itens utilizáveis.')+(p.invalid.length?`<div class="notice">${p.invalid.map(item=>`Linha ${item.line}: ${e(item.error)}`).join('<br>')}</div>`:'')+`<p class="hint">Somente administrador pode confirmar. Editar ou ignorar exige justificativa; toda decisão e arquivo ficam no histórico.</p><div class="modal-actions">${btn('Cancelar','closeModal()','alt')}${currentUser()?.isAdmin?btn('Aprovar e aplicar','confirmFinancialImport()'):'<span class="hint">Aguardando aprovação de administrador.</span>'}</div>`);}catch(error){toast(error.message);}}
async function confirmFinancialImport(){const p=App.financialImportPreview;if(!p||!currentUser()?.isAdmin)return toast('Somente administrador pode aprovar esta importação.');const decisions=p.rows.map((item,index)=>{const row=$('#modal').querySelectorAll('tbody tr')[index];return {id:item.id,classId:row.querySelector('[data-financial-class]').value,category:row.querySelector('[data-financial-category]').value,percent:row.querySelector('[data-financial-percent]').value,quantity:row.querySelector('[data-financial-quantity]').value,action:row.querySelector('[data-financial-action]').value,reason:row.querySelector('[data-financial-reason]').value};});if(decisions.some(item=>['edit','ignore'].includes(item.action)&&!item.reason.trim()))return toast('Informe justificativa para cada item editado ou ignorado.');try{const result=await api('financial-classifications/confirm',{token:p.token,decisions,confirmation:'APROVAR IMPORTAÇÃO FINANCEIRA'});S=M.migrate(result.state);App.version=result.version;App.financialImportPreview=null;closeModal();render();toast('Importação financeira aprovada; receitas e ponto de equilíbrio foram recalculados.');}catch(error){toast(error.message);}}
function revenue2027(){return (S.revenuePlanning?.years||{})['2027']||{year:2027,calendar:{enrollmentMonth:1,tuitionMonths:[2,3,4,5,6,7,8,9,10,11,12]},campaigns:[],imports:[],records:[]};}
function revenue2027Panel(){const r=revenue2027(),records=r.records||[],net=records.reduce((sum,row)=>sum+Number(row.net||0)*Number(row.direction??1),0),divergences=records.filter(row=>row.financialDivergence!=null&&Math.abs(Number(row.financialDivergence))>.005),campaigns=(r.campaigns||[]).map(row=>`<tr><td><b>${e(row.name)}</b></td><td>${dateLabel(row.startDate)} a ${dateLabel(row.endDate)}</td><td>${row.discountPercent}%</td><td>${row.appliesEnrollment?'Sim':'Não'}</td><td>${(row.exceptions||[]).length} aluno(s) · ${(row.classExceptions||[]).length} turma(s)</td></tr>`).join('');return card('Receita 2027 · janeiro: matrícula | fevereiro a dezembro: 11 mensalidades',metrics([['Registros consolidados',records.length],['Receita líquida registrada',money(net)],['Divergências com baixas',divergences.length],['Versões importadas',(r.imports||[]).length]])+`<p class="hint">Matrícula não é tratada como 12ª mensalidade. Somente registros com identificador único de aluno e identificador financeiro podem ser aprovados.</p>`+table(['Campanha','Período','Desconto','Aplica à matrícula','Exceções'],campaigns,5,'Nenhuma campanha cadastrada.')+`<div class="head-actions">${currentUser()?.isAdmin?btn('+ Campanha de matrícula','openRevenueCampaign()','alt small')+btn('Importar arquivo consolidado','openRevenueImport()','alt small'):''}</div>`+table(['Arquivo / versão','Itens','Pendentes','Duplicados','Aprovado por'],(r.imports||[]).slice().reverse().map(item=>`<tr><td>${e(item.name)} · v${item.version}</td><td>${item.count}</td><td>${item.pending}</td><td>${item.duplicates}</td><td>${e(item.approvedBy)}</td></tr>`).join(''),5,'Nenhuma importação aprovada.'))}
function openRevenue2027(){modal('Receita 2027',revenue2027Panel()+`<div class="modal-actions">${btn('Fechar','closeModal()','alt')}</div>`)}
function openRevenueCampaign(){if(!currentUser()?.isAdmin)return toast('Somente administrador pode cadastrar campanhas.');modal('Campanha de matrícula 2027',`<p class="hint">A campanha só pode ser aplicada a matrículas em janeiro. Exceções recebem identificadores únicos de aluno, separados por vírgula; não use nomes.</p>`+form([['campaignName','Nome da campanha','text'],['campaignStart','Início','date',null,'2027-01-01'],['campaignEnd','Fim','date',null,'2027-01-31'],['campaignDiscount','Desconto (%)','number',null,0],['campaignExceptions','IDs de alunos excluídos','text'],['campaignClassExceptions','Turmas excluídas',null,`<select id="f_campaignClassExceptions" multiple>${S.classes.map(c=>`<option value="${e(c.id)}">${e(c.name)}</option>`).join('')}</select>`]])+actions('saveRevenueCampaign()'));}
function saveRevenueCampaign(){commit('financial','create',s=>{if(!currentUser()?.isAdmin)throw Error('Somente administrador pode cadastrar campanhas.');s.revenuePlanning=s.revenuePlanning||{years:{}};const years=s.revenuePlanning.years=s.revenuePlanning.years||{},r=years['2027']=years['2027']||{year:2027,calendar:{enrollmentMonth:1,tuitionMonths:[2,3,4,5,6,7,8,9,10,11,12]},campaigns:[],imports:[],records:[]},discount=numval('campaignDiscount'),start=val('campaignStart'),end=val('campaignEnd');if(!val('campaignName')||!/^2027-01-\d{2}$/.test(start)||!/^2027-01-\d{2}$/.test(end)||end<start||discount<0||discount>100)throw Error('Informe nome, período em janeiro de 2027 e desconto entre 0% e 100%.');r.campaigns.push({id:uid(),name:val('campaignName'),startDate:start,endDate:end,discountPercent:discount,appliesEnrollment:true,exceptions:val('campaignExceptions').split(',').map(x=>x.trim()).filter(Boolean),classExceptions:Array.from($('#f_campaignClassExceptions').selectedOptions).map(x=>x.value),createdAt:new Date().toISOString(),createdBy:currentUser().name,createdById:currentUser().id});},'Campanha registrada. Nenhuma receita existente foi alterada.');}
function openRevenueImport(){if(!financialAllowed('edit'))return;if(App.mode!=='shared')return toast('A importação consolidada exige o servidor compartilhado.');modal('Importar receitas consolidadas 2027',`<p class="hint">Priorize XLSX ou CSV; PDF somente quando a tabela textual for confiável. Um único arquivo pode conter todas as turmas, mas cada linha precisa de ID único do aluno e ID financeiro do lançamento.</p><div class="form-row"><label>Arquivo<input id="revenueImportFile" type="file" accept=".xlsx,.csv,.pdf"></label></div><p class="hint">Colunas: ID aluno, ID lançamento, Turma, Tipo, Data, Valor bruto, Desconto, Status; opcionais: Baixa financeira, Estorno de, Turma origem.</p><div class="modal-actions">${btn('Cancelar','closeModal()','alt')}${btn('Gerar prévia','previewRevenueImport()')}</div>`);}
async function previewRevenueImport(){const file=$('#revenueImportFile')?.files[0];if(!file)return toast('Selecione o arquivo consolidado.');if(file.size>10*1024*1024)return toast('Limite de 10 MB por arquivo.');try{const p=await api('revenue-2027/preview',{name:file.name,content:await asBase64(file),year:2027});App.revenuePreview=p;const rows=p.rows.map((item,index)=>`<tr><td>${item.line}</td><td>${e(item.studentId)}</td><td>${e(item.externalId)}</td><td>${e(item.className)}</td><td>${e(item.eventType)}</td><td>${dateLabel(item.date)}</td><td>${money(item.gross)} / ${money(item.discount)} / <b>${money(item.net)}</b></td><td>${e(item.campaignName||'—')}</td><td>${e(item.status)}</td><td>${item.financialDivergence==null?'Não informado':money(item.financialDivergence)}</td><td><select data-revenue-action><option value="accept" ${item.statusReview==='ready'?'selected':''}>Aceitar</option><option value="ignore">Ignorar</option></select><input data-revenue-reason placeholder="Justificativa obrigatória ao ignorar"></td><td>${e(item.reason)}</td></tr>`).join('');modal('Prévia obrigatória · receitas consolidadas',`<p><b>${e(p.name)}</b> · ${p.rows.length} linha(s) · ${p.ready} pronta(s) · ${p.pending} pendente(s) · ${p.duplicates} duplicidade(s).</p>`+table(['Linha','ID aluno','ID financeiro','Turma','Evento','Data','Bruto / desc. / líquido','Campanha','Status','Divergência baixa','Decisão','Validação'],rows,12,'Nenhuma linha utilizável.')+(p.invalid.length?`<div class="notice">${p.invalid.map(x=>`Linha ${x.line}: ${e(x.error)}`).join('<br>')}</div>`:'')+`<p class="hint">Pendente, duplicada, cancelada ou estornada sem lançamento original não pode ser aplicada. A confirmação gera nova versão e auditoria.</p><div class="modal-actions">${btn('Cancelar','closeModal()','alt')}${currentUser()?.isAdmin?btn('Aprovar importação','confirmRevenueImport()'):'<span class="hint">Aguardando administrador.</span>'}</div>`);}catch(error){toast(error.message);}}
async function confirmRevenueImport(){const p=App.revenuePreview;if(!p||!currentUser()?.isAdmin)return toast('Somente administrador pode aprovar.');const decisions=p.rows.map((item,index)=>{const row=$('#modal').querySelectorAll('tbody tr')[index];return {id:item.id,action:row.querySelector('[data-revenue-action]').value,reason:row.querySelector('[data-revenue-reason]').value};});if(decisions.some(x=>x.action==='ignore'&&!x.reason.trim()))return toast('Justifique cada item ignorado.');try{const result=await api('revenue-2027/confirm',{token:p.token,decisions,confirmation:'APROVAR RECEITAS CONSOLIDADAS'});S=M.migrate(result.state);App.version=result.version;App.revenuePreview=null;closeModal();render();toast('Receitas consolidadas aprovadas em nova versão; PE definitivo continua condicionado à conciliação de custos e rateios.');}catch(error){toast(error.message);}}
const executiveDashboard=dashboard;
dashboard=function(){let html=executiveDashboard();const start=html.indexOf('<div class="metrics">'),end=html.indexOf('<div class="dashboard-grid">');html=html.slice(0,start)+enrollmentMetrics()+reconciliationNotice()+html.slice(end);html=html.replace('Dados deste navegador',connectionLabel());html=html.replace('<small>Financeira</small><strong>'+money(S.delinquency.financial),'<small>Financeira (%)</small><strong>'+optionalPercent(S.delinquency.financialPercent)).replace('<small>Contábil</small><strong>'+money(S.delinquency.accounting),'<small>Contábil (%)</small><strong>'+optionalPercent(S.delinquency.accountingPercent));if(currentUser()?.isAdmin)html+=requestCounters();return html;};
enrollments=function(){const actions=`<div class="head-actions">${btn('Atualizar dados','refreshCurrentPage()','alt')}${allowedButton('enrollments','create','+ Registrar lançamento','openEnrollment()','')}${allowedButton('classes','create','+ Nova turma','openClass()','alt')}${currentUser()?.isAdmin?btn('Definir meta','openMeta()','alt'):''}</div>`,finance=financialAllowed()?card('Visão financeira · '+financeYear,financeControls()+financialSummary()+`<p class="hint">Projeção financeira provisória: ${M.financialTotals(S,financeYear).unclassifiedFinancial} aluno(s) ainda não classificado(s) financeiramente.</p>${btn('Abrir parâmetros financeiros',"go('financial')",'alt small')}`):'';return head('Matrículas','Base única com Turmas e Vagas. Todos os totais são quantitativos.',actions)+enrollmentMetrics()+reconciliationNotice()+finance+card('Resumo por turma',classFilter()+classTable(true))+card('Histórico de lançamentos',table(['Data','Tipo','Turma','Quantidade','Usuário','Ações'],S.enrollments.history.slice().reverse().map(h=>`<tr><td>${dateLabel(h.date)}</td><td>${h.type==='re'?'Rematrícula':'Nova matrícula'}</td><td>${e(findBy(S.classes,h.classId)?.name||h.className||'Turma não vinculada')}</td><td>${h.quantity}</td><td>${e(h.user)}</td><td>${allowedButton('enrollments','edit','✎ Editar',`openEnrollment(${jsid(h.id)})`)} ${allowedButton('enrollments','delete','⌫ Excluir',`deleteRecord('enrollments',${jsid(h.id)})`,'danger small')}</td></tr>`).join(''),6,'Nenhum lançamento registrado.'));};
classes=function(){const t=M.totals(S);return head('Turmas e Vagas','Ocupação calculada com as mesmas matrículas do painel e dos relatórios.',allowedButton('classes','create','+ Nova turma','openClass()',''))+metrics([['Turmas',S.classes.length],['Total matriculados',t.total],['Vagas disponíveis',t.vacancies],['Atenção / lotadas / acima',`${t.attention} / ${t.full} / ${t.above}`]])+reconciliationNotice()+classFilter()+classTable(true);};
openMeta=function(){if(!currentUser()?.isAdmin)return toast('Somente administradores podem alterar a meta.');const target=M.totals(S).goal;modal('Definir meta de matrículas',form([['meta','Meta total de alunos','number',null,target]])+actions('saveMeta()'));};
function saveMeta(){commit('enrollments','edit',s=>{const target=numval('meta');if(!M.integer(target)||target<1)throw Error('Informe uma meta inteira positiva.');s.meta=target;},'Meta de matrículas atualizada.');}
openClass=function(value){const c=findBy(S.classes,value)||{};modal(c.id?'Editar turma':'Nova turma',form([['name','Nome da turma','text',null,c.name],['stage','Etapa',null,`<select id="f_stage">${[...educationStages,'Outra / não classificada'].map(stage=>`<option value="${e(stage)}" ${(c.stage||'Outra / não classificada')===stage?'selected':''}>${e(stage)}</option>`).join('')}</select>`],['capacity','Capacidade total','number',null,c.capacity||'']])+`<p class="hint">Rematrículas e alunos novos são quantitativos independentes; o total é calculado automaticamente.</p>`+actions(`saveClass(${value?jsid(value):'null'})`));};
function saveClass(value){commit('classes',value?'edit':'create',s=>{const old=findBy(s.classes,value),capacity=val('capacity')===''?0:numval('capacity'),data={name:val('name'),stage:val('stage'),capacity,template:false};if(old)Object.assign(old,data);else s.classes.push({id:uid(),...data,opening:{new:0,re:0},unclassified:0,students:0});});}
function deleteClass(value){const room=findBy(S.classes,value),entries=S.enrollments.history.filter(x=>String(x.classId)===String(value));if(!room)return;if(entries.length)return toast('Esta turma possui lançamentos. Corrija ou exclua os lançamentos antes de excluir a turma.');modal('Excluir turma',`<p>Excluir a turma <b>${e(room.name)}</b>? Nenhum lançamento será removido.</p><div class="modal-actions">${btn('Cancelar','closeModal()','alt')}${btn('⌫ Excluir',`confirmDelete('classes',${jsid(value)})`,'danger')}</div>`);}
openEnrollment=function(value){if(!S.classes.length)return toast('Solicite ao administrador o cadastro da turma.');const h=findBy(S.enrollments.history,value)||{};modal(h.id?'Editar lançamento':'Registrar lançamento',form([['type','Tipo',null,`<select id="f_type"><option value="new">Nova matrícula</option><option value="re" ${h.type==='re'?'selected':''}>Rematrícula</option></select>`],['class','Turma',null,`<select id="f_class">${S.classes.map(c=>`<option value="${e(c.id)}" ${String(c.id)===String(h.classId)?'selected':''}>${e(c.name)}</option>`).join('')}</select>`],['quantity','Quantidade','number',null,h.quantity??1],['date','Data','date',null,h.date||localDate()]])+actions(`saveEnrollment(${value?jsid(value):'null'})`));};
saveEnrollment=function(value){commit('enrollments',value?'edit':'create',s=>{const c=findBy(s.classes,val('class'));if(!c)throw Error('Turma não encontrada.');const entry={classId:c.id,className:c.name,type:val('type'),quantity:numval('quantity'),date:val('date')};const previous=findBy(s.enrollments.history,value);if(previous)Object.assign(previous,entry,{updatedBy:currentUser().name,updatedAt:new Date().toISOString()});else s.enrollments.history.push({id:uid(),...entry,user:currentUser().name,userId:currentUser().id});});};
function openingPreview(value){const c=findBy(S.classes,value);if(!c)return '';const field=(name,fallback)=>$('#f_'+name)?numval(name):n(fallback),preview={...c,capacity:field('capacity',c.capacity),opening:{new:field('new',c.opening?.new),re:field('re',c.opening?.re)},unclassified:field('unclassified',c.unclassified)},x=M.classStats(S,preview),label=x.status==='above'?'Acima da capacidade':x.status==='full'?'Lotada':x.status==='attention'?'Próxima da capacidade':'Dentro da capacidade';return `<h3>Resumo após alteração</h3><div class="preview-grid"><div><span>Total matriculados</span><b>${x.total}</b></div><div><span>Capacidade</span><b>${x.capacity}</b></div><div><span>Vagas disponíveis</span><b>${x.vacancies}</b></div><div><span>Ocupação</span><b>${x.occupancy==null?'Sem capacidade':formatPct(x.occupancy)}</b></div><div class="preview-status"><span>Situação</span><b>${label}</b></div></div>${x.excess?`<p class="preview-alert">Atenção: esta turma ficará acima da capacidade em ${x.excess} aluno(s).</p>`:''}`;}
function refreshOpeningPreview(value){const target=$('#openingPreview');if(target)target.innerHTML=openingPreview(value);}
function openingField(name,label,value,oninput,description=''){return `<div class="field"><label for="f_${name}">${label}</label><input id="f_${name}" type="number" min="0" step="1" value="${e(value)}" oninput="${oninput}">${description?`<small>${description}</small>`:''}</div>`;}
function openOpening(value){if(!canEditEnrollmentQuantities())return toast('Seu perfil não permite editar os quantitativos de matrícula.');const c=findBy(S.classes,value);if(!c)return;const update=`refreshOpeningPreview(${jsid(value)})`,capacity=currentUser()?.isAdmin?openingField('capacity','Capacidade da turma',c.capacity??0,update):`<div class="field"><label for="f_capacity">Capacidade da turma</label><input id="f_capacity" type="number" value="${e(c.capacity??0)}" readonly aria-readonly="true"><small>Somente administradores podem alterar a capacidade.</small></div>`,fields=`<div class="form">${capacity}${openingField('new','Alunos novos',c.opening?.new??0,update)}${openingField('re','Rematrículas',c.opening?.re??0,update)}${openingField('unclassified','Matriculados ainda não classificados',c.unclassified??0,update,'Alunos matriculados que ainda não foram classificados como rematrícula ou aluno novo.')}</div>`;modal('Editar quantitativos · '+e(c.name),`<p class="hint">O total matriculado é recalculado como alunos novos + rematrículas + matriculados ainda não classificados. Lançamentos do histórico continuam somados separadamente.</p>${fields}<section id="openingPreview" class="opening-preview">${openingPreview(value)}</section>`+actions(`saveOpening(${jsid(value)})`));}
function saveOpening(value){if(!canEditEnrollmentQuantities())return toast('Seu perfil não permite editar os quantitativos de matrícula.');commit('enrollments','edit',s=>{const c=findBy(s.classes,value);if(currentUser()?.isAdmin)c.capacity=numval('capacity');c.opening={new:numval('new'),re:numval('re')};c.unclassified=numval('unclassified');},'Quantitativos atualizados; total, vagas, ocupação e situação foram recalculados.');}
function deleteRecord(module,value){if(!can(module,'delete'))return toast('Exclusão não autorizada.');modal('Confirmar exclusão',`<p>Excluir este registro? A auditoria será preservada${module==='enrollments'?' e os totais serão recalculados':''}.</p><div class="modal-actions">${btn('Cancelar','closeModal()','alt')}${btn('Excluir',`confirmDelete('${module}',${jsid(value)})`,'danger')}</div>`);}
function confirmDelete(module,value){commit(module,'delete',s=>{if(module==='enrollments')s.enrollments.history=s.enrollments.history.filter(x=>String(x.id)!==String(value));else s[module]=s[module].filter(x=>String(x.id)!==String(value));},'Registro excluído; auditoria preservada.');}

benefits=function(){return head('Benefícios','Cadastro, situação e histórico de alterações.',allowedButton('benefits','create','+ Novo benefício','openBenefit()',''))+metrics([['Benefícios',S.benefits.length],['Ativos',S.benefits.filter(x=>x.active).length],['Inativos',S.benefits.filter(x=>!x.active).length],['Quantidade ativa',S.benefits.filter(x=>x.active).reduce((a,x)=>a+n(x.quantity),0)]])+table(['Benefício','Tipo','Quantidade','Situação','Ações'],S.benefits.map(x=>`<tr><td>${e(x.name)}</td><td>${e(x.type)}</td><td>${x.quantity}</td><td><span class="pill ${x.active?'normal':''}">${x.active?'Ativo':'Inativo'}</span></td><td>${allowedButton('benefits','edit','Editar',`openBenefit(${jsid(x.id)})`)} ${btn('Histórico',`recordHistory('benefits',${jsid(x.id)})`,'alt small')} ${allowedButton('benefits','delete','Excluir',`deleteRecord('benefits',${jsid(x.id)})`,'danger small')}</td></tr>`).join(''),5,'Nenhum benefício cadastrado.');};
openBenefit=function(value){const x=findBy(S.benefits,value)||{};modal(value?'Editar benefício':'Novo benefício',form([['name','Nome','text',null,x.name],['type','Tipo','text',null,x.type],['quantity','Quantidade','number',null,x.quantity??0],['active','Situação',null,`<select id="f_active"><option value="true">Ativo</option><option value="false" ${x.active===false?'selected':''}>Inativo</option></select>`]])+actions(`saveBenefit(${value?jsid(value):'null'})`));};
function saveBenefit(value){commit('benefits',value?'edit':'create',s=>{const old=findBy(s.benefits,value),data={name:val('name'),type:val('type'),quantity:numval('quantity'),active:val('active')==='true'};if(old){const before=M.clone(old);Object.assign(old,data);old.history=[...(old.history||[]),...M.auditDiff(before,data,currentUser(),'benefits','edit')];}else s.benefits.push({id:uid(),...data,history:M.auditDiff({},data,currentUser(),'benefits','create')});});}
function recordHistory(module,value){const x=findBy(S[module],value);const entries=x?.history||[];modal('Histórico de alterações',table(['Usuário','Data/hora','Informação','Anterior','Novo'],entries.map(h=>`<tr><td>${e(h.user)}</td><td>${e(new Date(h.date).toLocaleString('pt-BR'))}</td><td>${e(h.field)}</td><td>${e(h.before??'—')}</td><td>${e(h.after??'—')}</td></tr>`).join(''),5,'Sem alterações detalhadas registradas.')+`<div class="modal-actions">${btn('Fechar','closeModal()','alt')}</div>`);}

Object.assign(labels,{waiting:'Aguardando aprovação',rejected:'Reprovada'});
let requestView='all';
function requestCounters(){const mine=currentUser()?.id,rows=S.requests;return `<div class="request-counters">${[['received','Recebidas',rows.filter(x=>x.recipientId===mine).length],['sent','Enviadas por mim',rows.filter(x=>x.creatorId===mine).length],['waiting','Aguardando aprovação',rows.filter(x=>x.status==='waiting').length],['doing','Em andamento',rows.filter(x=>x.status==='doing').length],['late','Vencidas',rows.filter(x=>x.due&&x.due<localDate()&&!['completed','rejected'].includes(x.status)).length],['completed','Concluídas',rows.filter(x=>x.status==='completed').length]].map(([key,label,value])=>`<button class="stat" onclick="requestView='${key}';go('requests')"><b>${value}</b><small>${label}</small></button>`).join('')}</div>`;}
function visibleRequests(){return S.requests.filter(x=>requestView==='all'||requestView==='received'&&x.recipientId===currentUser()?.id||requestView==='sent'&&x.creatorId===currentUser()?.id||requestView==='late'&&x.due&&x.due<localDate()&&!['completed','rejected'].includes(x.status)||x.status===requestView);}
requests=function(){return head('Central de Solicitações','Solicitada → Aguardando aprovação → Aprovada/Reprovada → Em andamento → Concluída.',`<div class="head-actions">${allowedButton('requests','create','+ Nova solicitação','openRequest()','')}${currentUser()?.isAdmin?btn('Apagar tudo','purgeRequests()','danger'):''}</div>`)+requestCounters()+`<div class="filter-tabs">${btn('Todas',"requestView='all';render()",'alt small')}<span>${e(requestView==='all'?'Todas as solicitações':'Filtro: '+({received:'Recebidas',sent:'Enviadas por mim',waiting:'Aguardando aprovação',doing:'Em andamento',late:'Vencidas',completed:'Concluídas'}[requestView]||requestView))}</span></div>`+table(['Solicitação','Enviada por / para','Prazo','Status','Ações'],visibleRequests().map(x=>`<tr><td><b>${e(x.title)}</b><br><small>${e(x.description)}</small></td><td>${e(x.creatorName||x.requestedBy)}<br>→ ${e(x.recipientName||x.owner)}</td><td>${dateLabel(x.due)}</td><td><span class="pill ${x.status}">${labels[x.status]||e(x.status)}</span>${x.status==='rejected'?`<p class="text-danger">${e(x.rejectionReason||'Motivo não registrado na versão anterior.')}</p>`:''}</td><td>${btn('Acompanhar',`requestDetail(${jsid(x.id)})`,'alt small')} ${allowedButton('requests','edit','Editar',`openRequest(${jsid(x.id)})`)} ${allowedButton('requests','delete','Excluir',`deleteRecord('requests',${jsid(x.id)})`,'danger small')}</td></tr>`).join(''),5,'Nenhuma solicitação neste filtro.');};
openRequest=function(value){const x=findBy(S.requests,value)||{},people=S.users.filter(u=>u.active!==false&&!u.deleted&&(currentUser()?.isAdmin||u.isAdmin));modal(value?'Editar solicitação':'Nova solicitação',form([['title','Título','text',null,x.title],['description','Descrição',null,`<textarea id="f_description">${e(x.description)}</textarea>`],['recipient','Enviar para',null,`<select id="f_recipient"><option value="">Selecione um usuário ativo</option>${people.map(u=>`<option value="${e(u.id)}" ${u.id===x.recipientId?'selected':''}>${e(u.name)}</option>`).join('')}</select>`],['due','Prazo','date',null,x.due],['phone','WhatsApp do solicitante','tel',null,x.requesterPhone||currentUser()?.phone]])+`<p class="hint">Notificações serão registradas na fila; não há envio de WhatsApp sem API oficial configurada.</p>`+actions(`saveRequest(${value?jsid(value):'null'})`));};
function saveRequest(value){commit('requests',value?'edit':'create',s=>{const person=findBy(s.users,val('recipient'));if(!person)throw Error('Selecione um destinatário ativo cadastrado.');const data={title:val('title'),description:val('description'),recipientId:person.id,recipientName:person.name,owner:person.name,due:val('due'),requesterPhone:val('phone')};const old=findBy(s.requests,value);if(old)Object.assign(old,data);else{const r={id:uid(),...data,status:'requested',creatorId:currentUser().id,creatorName:currentUser().name,requestedBy:currentUser().name,createdAt:new Date().toISOString(),history:[],comments:[]};s.requests.push(r);queueLocalNotification(s,r,'requested');}});}
function queueLocalNotification(s,r,event){if(App.mode==='shared')return;s.notifications.push({id:uid(),requestId:r.id,userId:r.creatorId,phone:r.requesterPhone,event,createdAt:new Date().toISOString(),attemptedAt:null,status:'awaiting_configuration',detail:'Sem API configurada. Nenhum envio realizado.'});}
function requestDetail(value){const r=findBy(S.requests,value);const flow={requested:['waiting'],waiting:['approved','rejected'],approved:['doing'],rejected:['waiting'],doing:['completed'],completed:[]};modal('Acompanhar solicitação',`<h3>${e(r.title)}</h3><p>${e(r.description)}</p><div class="head-actions">${(flow[r.status]||[]).map(status=>allowedButton('requests',['approved','rejected'].includes(status)?'approve':'edit',labels[status],`changeRequestStatus(${jsid(value)},'${status}')`)).join('')}</div><h3>Histórico</h3><div class="list">${(r.history||[]).map(x=>`<div class="row"><span>${e(x.user||'Autor não registrado')} · ${e(labels[x.status]||x.status)}${x.reason?'<br>'+e(x.reason):''}</span><small>${e(new Date(x.date).toLocaleString('pt-BR'))}</small></div>`).join('')||'<p class="hint">Nenhuma transição registrada.</p>'}</div><h3>Comentários</h3>${(r.comments||[]).map(c=>`<p><b>${e(c.user)}</b> · ${e(new Date(c.date).toLocaleString('pt-BR'))}<br>${e(c.text)}</p>`).join('')}${can('requests','edit')?form([['comment','Adicionar comentário',null,'<textarea id="f_comment" rows="3"></textarea>']])+btn('Adicionar comentário',`addComment(${jsid(value)})`,'alt'):''}<h3>Notificações</h3>${S.notifications.filter(x=>String(x.requestId)===String(value)).map(x=>`<p class="hint">${e(labels[x.event]||x.event)} · ${e(x.status==='awaiting_configuration'?'Aguardando configuração':x.status)}<br>${e(x.detail)}<br>Tentativa: ${x.attemptedAt?e(new Date(x.attemptedAt).toLocaleString('pt-BR')):'não realizada'}</p>`).join('')||'<p class="hint">Nenhum evento de notificação registrado.</p>'}<div class="modal-actions">${btn('Fechar','closeModal()','alt')}</div>`);}
function changeRequestStatus(value,status){if(status==='rejected'){modal('Reprovar solicitação',form([['reason','Motivo da reprovação',null,'<textarea id="f_reason" required rows="4"></textarea>']])+actions(`confirmStatus(${jsid(value)},'rejected')`));}else confirmStatus(value,status);}
function confirmStatus(value,status){const reason=status==='rejected'?val('reason'):'';if(status==='rejected'&&!reason)return toast('Preencha o motivo da reprovação.');commit('requests',['approved','rejected'].includes(status)?'approve':'edit',s=>{const r=findBy(s.requests,value);r.status=status;if(status==='rejected')r.rejectionReason=reason;r.history=[...(r.history||[]),{date:new Date().toISOString(),user:currentUser().name,userId:currentUser().id,status,reason}];queueLocalNotification(s,r,status);});}
function addComment(value){const text=val('comment');if(!text)return toast('Digite o comentário.');commit('requests','edit',s=>{const r=findBy(s.requests,value);r.comments=[...(r.comments||[]),{id:uid(),text,user:currentUser().name,userId:currentUser().id,date:new Date().toISOString()}];});}
function purgeRequests(){if(!currentUser()?.isAdmin)return;modal('Apagar todas as solicitações — etapa 1 de 2',`<p>Serão excluídas ${S.requests.length} solicitações. Os registros de auditoria e notificações serão preservados.</p><div class="modal-actions">${btn('Cancelar','closeModal()','alt')}${btn('Continuar para confirmação','purgeConfirm()','danger')}</div>`);}
function purgeConfirm(){modal('Confirmação final — etapa 2 de 2',`<p>Digite exatamente <b>APAGAR TODAS AS SOLICITAÇÕES</b>.</p>${form([['confirm','Confirmação','text']])}<div class="modal-actions">${btn('Cancelar','closeModal()','alt')}${btn('Apagar tudo','executePurge()','danger')}</div>`);}
function executePurge(){if(val('confirm')!=='APAGAR TODAS AS SOLICITAÇÕES')return toast('A confirmação não confere.');commit('requests','delete',s=>{s.requests=[];},'Solicitações excluídas; auditoria preservada.','APAGAR TODAS AS SOLICITAÇÕES');}

budget=function(){const t=totals();return head('Despesas Gerais 2026','Escopo exclusivo: DESPESAS 2026. Saldos anteriores preservados para conferência.',`<div class="head-actions">${allowedButton('budget','create','+ Conta','openBudget()','')}${allowedButton('budget','edit','Importar orçamento',"openSafeImport('budget')")}${allowedButton('budget','edit','Importar realizadas',"openSafeImport('expenses')")}</div>`)+metrics([['Orçado',money(t.planned)],['Realizado',money(t.actual)],['Disponível',money(t.remaining)],['Executado',t.planned?formatPct(t.actual/t.planned*100):'Não definido']])+table(['Categoria/Conta','Código','Orçado','Realizado','Disponível','% Executado','Última atualização','Ações'],S.budget.map(x=>`<tr><td>${e(x.category)}</td><td>${e(x.code||'—')}</td><td>${money(x.budget)}</td><td>${money(x.actual)}</td><td class="${x.actual>x.budget?'text-danger':''}">${money(x.budget-x.actual)}</td><td>${x.budget?formatPct(x.actual/x.budget*100):'—'}</td><td>${x.updatedAt?e(new Date(x.updatedAt).toLocaleString('pt-BR')):'Anterior à auditoria'}</td><td>${allowedButton('budget','edit','Editar',`openBudget(${jsid(x.id)})`)} ${allowedButton('budget','edit','+ Despesa',`openExpense(${jsid(x.id)})`)} ${btn('Histórico',`viewExpenses(${jsid(x.id)})`,'alt small')}</td></tr>`).join(''),8,'Nenhuma conta cadastrada.')+card('Revisar classificação',table(['Data','Descrição / finalidade','Valor','Categoria sugerida','Ação'],S.reviewQueue.map(x=>`<tr><td>${dateLabel(x.date)}</td><td>${e(x.description||x.purpose)}</td><td>${money(x.value)}</td><td>${e(findBy(S.budget,x.accountId)?.category||'Sem sugestão segura')}</td><td>${allowedButton('budget','edit','Revisar',`openClassification(${jsid(x.id)})`)}</td></tr>`).join(''),5,'Nenhum lançamento aguardando revisão.'))+importHistory(['budget','expenses']);};
openBudget=function(value){const x=findBy(S.budget,value)||{};modal(value?'Editar conta':'Nova conta de 2026',form([['category','Categoria/Conta','text',null,x.category],['code','Código da conta','text',null,x.code],['budget','Valor orçado','number',null,x.budget??0]])+actions(`saveBudget(${value?jsid(value):'null'})`));};
function saveBudget(value){commit('budget',value?'edit':'create',s=>{const data={category:val('category'),code:val('code'),budget:numval('budget'),year:2026,updatedAt:new Date().toISOString()};const old=findBy(s.budget,value);if(old)Object.assign(old,data);else s.budget.push({id:uid(),...data,actual:0,expenses:[]});});}
openExpense=function(value){const x=findBy(S.budget,value);modal('Lançar despesa · '+e(x.category),form([['value','Valor','number',null,0],['date','Data','date',null,localDate()],['description','Descrição / finalidade','text']])+actions(`saveExpense(${jsid(value)})`));};
saveExpense=function(value){commit('budget','edit',s=>{const x=findBy(s.budget,value),amount=numval('value');if(!Number.isFinite(amount)||amount<=0||!val('description')||!/^2026-\d{2}-\d{2}$/.test(val('date')))throw Error('Informe valor positivo, descrição e data de 2026.');x.expenses=[...(x.expenses||[]),{id:uid(),value:amount,date:val('date'),description:val('description'),user:currentUser().name,userId:currentUser().id}];x.actual=Math.round((n(x.actual)+amount)*100)/100;x.updatedAt=new Date().toISOString();});};
viewExpenses=function(value){const x=findBy(S.budget,value);modal('Histórico de despesas',`<p>${e(x.category)} · realizado ${money(x.actual)}</p><p class="hint">Saldos anteriores permanecem sem detalhamento inventado.</p>`+table(['Data','Descrição','Usuário','Valor'],(x.expenses||[]).map(r=>`<tr><td>${dateLabel(r.date)}</td><td>${e(r.description||r.purpose)}</td><td>${e(r.user)}</td><td>${money(r.value)}</td></tr>`).join(''),4,'Nenhum lançamento detalhado.')+`<div class="modal-actions">${btn('Fechar','closeModal()','alt')}</div>`);};
function openClassification(value){const x=findBy(S.reviewQueue,value);modal('Confirmar classificação',`<p>${e(x.description||x.purpose)} · ${money(x.value)}</p>`+form([['account','Categoria/Conta',null,`<select id="f_account"><option value="">Selecione a conta</option>${S.budget.map(a=>`<option value="${e(a.id)}" ${a.id===x.accountId?'selected':''}>${e(a.code||'')} · ${e(a.category)}</option>`).join('')}</select>`]])+actions(`confirmClassification(${jsid(value)})`));}
function confirmClassification(value){commit('budget','edit',s=>{const r=findBy(s.reviewQueue,value),account=findBy(s.budget,val('account'));if(!r||!account)throw Error('Selecione uma conta.');if(s.budget.some(a=>(a.expenses||[]).some(x=>x.fingerprint===r.fingerprint)))throw Error('Lançamento já importado.');account.expenses=[...(account.expenses||[]),{...r,accountId:account.id,user:currentUser().name,userId:currentUser().id}];account.actual=Math.round((account.actual+r.value)*100)/100;account.updatedAt=new Date().toISOString();const signature=['subaccount','description','purpose'].map(k=>M.fold(r[k])).join('|');s.classificationRules.push({id:uid(),signature,accountId:account.id,user:currentUser().name,date:new Date().toISOString()});s.reviewQueue=s.reviewQueue.filter(x=>x.id!==r.id);});}
function importHistory(kinds){return card('Histórico de importações',table(['Arquivo','Data/hora','Lançamentos','Automáticos','Pendentes','Duplicados','Inválidos'],S.imports.filter(x=>kinds.includes(x.kind)).slice().reverse().map(x=>`<tr><td>${e(x.name)}</td><td>${e(new Date(x.date).toLocaleString('pt-BR'))}</td><td>${x.count}</td><td>${x.automatic}</td><td>${x.pending}</td><td>${x.duplicates}</td><td>${x.rejected}</td></tr>`).join(''),7,'Nenhuma importação processada e confirmada.'));}
function openSafeImport(kind){if(App.mode!=='shared')return modal('Importação segura',emptyState('Requer o servidor local','Inicie o servidor Python e entre com um usuário autorizado. A leitura de Excel/PDF e a confirmação transacional são feitas no servidor.')+`<div class="modal-actions">${btn('Fechar','closeModal()','alt')}</div>`);App.preview=null;modal('Importar '+({budget:'orçamento',expenses:'despesas realizadas',financial:'relatório financeiro',accounting:'relatório contábil'}[kind]),`<p class="hint">XLSX, CSV e PDF com texto selecionável. Nenhum valor será gravado antes da prévia e confirmação. Excel usa apenas DESPESAS 2026.</p><label for="importFile">Arquivo</label><input id="importFile" type="file" accept=".xlsx,.csv,.pdf">${['budget','expenses'].includes(kind)?'<p><label><input type="checkbox" id="confirmSource"> Confirmo que o arquivo corresponde exclusivamente a DESPESAS 2026.</label></p>':''}<div class="modal-actions">${btn('Cancelar','closeModal()','alt')}${btn('Gerar prévia',`previewImport('${kind}')`)}</div>`);}
function asBase64(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(Error('Falha ao ler arquivo.'));reader.readAsDataURL(file);});}
async function previewImport(kind){const file=$('#importFile')?.files[0];if(!file)return toast('Selecione o arquivo.');if(file.size>10*1024*1024)return toast('Limite de 10 MB por arquivo.');try{App.preview=await api('import/preview',{kind,name:file.name,content:await asBase64(file),sourceConfirmed:$('#confirmSource')?.checked||false});const p=App.preview;modal('Prévia — nenhuma alteração aplicada',`<p><b>${e(p.name)}</b> · ${p.rows.length} válidos · ${p.automatic} automáticos · ${p.pending} para revisão · ${p.duplicates} duplicados · ${p.invalid.length} inválidos.</p>`+table(['Linha','Dados identificados','Classificação'],p.rows.slice(0,100).map(r=>`<tr><td>${r.line}</td><td>${e(JSON.stringify(r))}</td><td>${e(r.reason||r.status)}</td></tr>`).join(''),3,'Sem linhas novas.')+(p.invalid.length?`<div class="notice">${p.invalid.map(x=>`Linha ${x.line}: ${e(x.error)}`).join('<br>')}</div>`:'')+`<p class="hint">Exibidas as primeiras 100 linhas. Na confirmação, todas as ${p.rows.length} linhas válidas serão processadas; classificações duvidosas ficam pendentes e não alteram o realizado.</p><div class="modal-actions">${btn('Cancelar','closeModal()','alt')}${btn('Confirmar importação','confirmImport()')}</div>`);}catch(error){toast(error.message);}}
async function confirmImport(){if(App.busy||!App.preview)return;App.busy=true;try{const result=await api('import/confirm',{token:App.preview.token,confirmation:'CONFIRMAR IMPORTAÇÃO'});S=M.migrate(result.state);App.version=result.version;App.preview=null;closeModal();render();toast('Importação confirmada.');}catch(error){toast(error.message);}finally{App.busy=false;}}

delinquency=function(){const d=S.delinquency,months=(d.monthly||[]).slice().sort((a,b)=>a.month.localeCompare(b.month));return head('Inadimplência','Percentuais financeiros e contábeis separados dos valores em reais.',`<div class="head-actions">${allowedButton('delinquency','edit','Editar indicadores','openDelinquency()','')}${allowedButton('delinquency','edit','Importar financeiro',"openSafeImport('financial')")}${allowedButton('delinquency','edit','Importar contábil',"openSafeImport('accounting')")}</div>`)+metrics([['Inadimplência Financeira (%)',optionalPercent(d.financialPercent)],['Inadimplência Contábil (%)',optionalPercent(d.accountingPercent)],['Dívida Financeira (R$)',money(d.debt)],['Alunos / responsáveis',`${n(d.students)} / ${n(d.guardians)}`]])+(d.financialPercent==null||d.accountingPercent==null?'<div class="notice">Percentuais ainda não informados. Valores monetários antigos foram preservados e não foram convertidos em percentuais sem uma base de cálculo.</div>':'')+card('Comparativo mensal — Financeira × Contábil',months.length?`<div class="legend"><span><i></i>Financeira</span><span><i class="yellow"></i>Contábil</span></div><div class="monthly-chart">${months.map(x=>`<div><b>${e(x.month)}</b><span>Financeira: ${optionalPercent(x.financialPercent)}</span>${meter(n(x.financialPercent))}<span>Contábil: ${optionalPercent(x.accountingPercent)}</span>${meter(n(x.accountingPercent),'yellow')}</div>`).join('')}</div>`:emptyState('Sem histórico mensal','Edite os indicadores com a competência ou importe os relatórios reais.'))+importHistory(['financial','accounting']);};
openDelinquency=function(){const d=S.delinquency;modal('Atualizar inadimplência',form([['month','Competência','month',null,d.month||localDate().slice(0,7)],['financialPercent','Financeira (%)','number',null,d.financialPercent??''],['accountingPercent','Contábil (%)','number',null,d.accountingPercent??''],['debt','Dívida financeira (R$)','number',null,d.debt??0],['students','Alunos afetados','number',null,d.students??0],['guardians','Responsáveis afetados','number',null,d.guardians??0]])+actions('saveDelinquency()'));for(const k of ['financialPercent','accountingPercent']){const field=$('#f_'+k);field.step='0.01';field.max='100';field.required=false;}}
function saveDelinquency(){commit('delinquency','edit',s=>{if(!/^\d{4}-\d{2}$/.test(val('month')))throw Error('Informe a competência.');const values={month:val('month'),financialPercent:val('financialPercent')===''?null:numval('financialPercent'),accountingPercent:val('accountingPercent')===''?null:numval('accountingPercent'),debt:numval('debt'),students:numval('students'),guardians:numval('guardians'),updatedAt:new Date().toISOString()};if(!M.integer(values.students)||!M.integer(values.guardians)||values.debt<0)throw Error('Valores não negativos e contagens inteiras são obrigatórios.');const monthly=s.delinquency.monthly||[],old=monthly.find(x=>x.month===values.month);if(old)Object.assign(old,values);else monthly.push(values);const latest=monthly.slice().sort((a,b)=>b.month.localeCompare(a.month))[0];Object.assign(s.delinquency,latest,{monthly});});}

guardians=function(){const incomplete=S.guardians.filter(x=>!x.phone||!x.name||!x.student);return head('Responsáveis','Contatos e referências não alteram matrículas nem indicadores financeiros.',allowedButton('guardians','create','+ Responsável','openGuardian()',''))+metrics([['Cadastros',S.guardians.length],['Sem WhatsApp',S.guardians.filter(x=>!x.phone).length],['Incompletos',incomplete.length],['Com e-mail',S.guardians.filter(x=>x.email).length]])+table(['Nome / vínculo','Telefone/WhatsApp','E-mail','Aluno / turma','Ações'],S.guardians.map(x=>`<tr><td>${e(x.name)}<br><small>${e(x.relationship)}</small></td><td>${e(x.phone)||'<span class="pill attention">Telefone não informado</span>'}</td><td>${e(x.email)||'—'}</td><td>${e(x.student)||'—'}<br><small>${e(findBy(S.classes,x.classId)?.name||x.className)}</small></td><td>${allowedButton('guardians','edit','Editar',`openGuardian(${jsid(x.id)})`)} ${allowedButton('guardians','delete','Excluir',`deleteRecord('guardians',${jsid(x.id)})`,'danger small')}</td></tr>`).join(''),5,'Nenhum responsável cadastrado.');};
openGuardian=function(value){const x=findBy(S.guardians,value)||{};modal(value?'Editar responsável':'Novo responsável',form([['name','Nome','text',null,x.name],['relationship','Vínculo','text',null,x.relationship],['phone','Telefone/WhatsApp','tel',null,x.phone],['email','E-mail','email',null,x.email],['student','Aluno de referência','text',null,x.student],['class','Turma',null,`<select id="f_class"><option value="">Não informada</option>${S.classes.map(c=>`<option value="${e(c.id)}" ${String(c.id)===String(x.classId)?'selected':''}>${e(c.name)}</option>`).join('')}</select>`]])+actions(`saveGuardian(${value?jsid(value):'null'})`));};
saveGuardian=function(value){commit('guardians',value?'edit':'create',s=>{if(!val('name'))throw Error('Informe o nome.');const data={name:val('name'),relationship:val('relationship'),phone:val('phone'),email:val('email'),student:val('student'),classId:val('class'),className:findBy(s.classes,val('class'))?.name||''};const old=findBy(s.guardians,value);if(old)Object.assign(old,data);else s.guardians.push({id:uid(),...data});});};

users=function(){return head('Administração de Usuários','Permissões por módulo, sessões revogáveis e histórico preservado.',App.mode==='shared'?allowedButton('users','create','+ Cadastrar usuário','openUser()',''):'')+(App.mode!=='shared'?'<div class="notice">Administração real disponível no servidor Python. Nenhuma conta ou senha será criada no armazenamento local.</div>':'')+table(['Nome','E-mail','Perfil','Situação','Ações'],S.users.filter(u=>!u.deleted).map(u=>`<tr><td>${e(u.name)}</td><td>${e(u.email||'Sem login cadastrado')}</td><td>${u.isAdmin?'Administrador':'Permissões por módulo'}</td><td>${u.active===false?'Inativo':'Ativo'}</td><td>${allowedButton('users','edit','Editar permissões',`openUser(${jsid(u.id)})`)} ${allowedButton('users','delete','Excluir',`deleteUser(${jsid(u.id)})`,'danger small')}</td></tr>`).join(''),5,'Nenhuma conta disponível.')+card('Configuração institucional',`<p class="hint">Use a logo original fornecida pela escola. Nenhuma logo substituta será criada.</p><input id="logoFile" type="file" accept="image/png,image/jpeg">${allowedButton('users','edit','Salvar logo','uploadLogo()')}<hr><p>Dados locais anteriores podem ser migrados uma única vez para uma base compartilhada vazia, com confirmação.</p>${allowedButton('users','create','Revisar migração local','reviewMigration()')}`);};
function openUser(value){if(App.mode!=='shared')return toast('Inicie o servidor e entre como administrador.');const u=findBy(S.users,value)||{};modal(value?'Editar usuário e permissões':'Cadastrar usuário',form([['name','Nome','text',null,u.name],['email','E-mail de acesso','email',null,u.email],['phone','Telefone/WhatsApp','tel',null,u.phone],['password',value?'Nova senha (opcional)':'Senha inicial (mínimo 12 caracteres)','password'],['active','Situação',null,`<select id="f_active"><option value="true">Ativo</option><option value="false" ${u.active===false?'selected':''}>Inativo</option></select>`],['admin','Administrador',null,`<select id="f_admin"><option value="false">Não</option><option value="true" ${u.isAdmin?'selected':''}>Sim — acesso administrativo</option></select>`]])+`<p class="hint">Ao editar, as sessões deste usuário serão encerradas. Para Lívia, mantenha as autorizações atuais, habilite Visualizar em Turmas e Vagas e mantenha Editar em Matrículas. Não marque criar/excluir turmas, usuários ou administração.</p><div class="permissions-grid">${M.modules.map(module=>`<fieldset><legend>${e(nav.find(x=>x[1]===module)?.[0]||module)}</legend>${['view','create','edit','delete',...(module==='requests'?['approve']:[])].map(action=>`<label><input type="checkbox" data-module="${module}" data-action="${action}" ${u.access?.[module]?.includes(action)?'checked':''}>${{view:'Visualizar',create:'Criar',edit:'Editar',delete:'Excluir',approve:'Aprovar'}[action]}</label>`).join('')}</fieldset>`).join('')}</div>`+actions(`saveUser(${value?jsid(value):'null'})`));}
async function saveUser(value){const access={};$('#modal').querySelectorAll('input[data-module]:checked').forEach(input=>{(access[input.dataset.module]??=[]).push(input.dataset.action);});const user={id:value||undefined,name:val('name'),email:val('email'),phone:val('phone'),password:val('password')||undefined,active:val('active')==='true',isAdmin:val('admin')==='true',access};try{await api('users',{action:value?'edit':'create',user});closeModal();await refreshShared();toast('Usuário salvo; sessões anteriores revogadas.');}catch(error){toast(error.message);}}
function deleteUser(value){modal('Excluir usuário',`<p>O acesso e as sessões serão encerrados. O histórico continuará associado ao nome e identificador originais.</p><div class="modal-actions">${btn('Cancelar','closeModal()','alt')}${btn('Excluir',`confirmDeleteUser(${jsid(value)})`,'danger')}</div>`);}
async function confirmDeleteUser(value){try{await api('users',{action:'delete',user:{id:value}});closeModal();await refreshShared();}catch(error){toast(error.message);}}
async function uploadLogo(){const file=$('#logoFile')?.files[0];if(!file)return toast('Selecione a logo institucional.');try{await api('logo',{content:await asBase64(file)});toast('Logo salva para cabeçalho e marca-d’água.');}catch(error){toast(error.message);}}
function reviewMigration(){const source=M.migrate(App.legacy);modal('Revisar migração dos dados locais',`<p>${source.classes.length} turmas · ${source.enrollments.history.length} lançamentos · ${source.benefits.length} benefícios · ${source.requests.length} solicitações · ${source.budget.length} contas.</p><p>As contas de login não serão importadas. A base compartilhada precisa estar vazia. A cópia local será mantida.</p><div class="modal-actions">${btn('Cancelar','closeModal()','alt')}${btn('Confirmar migração','migrateLocal()')}</div>`);}
async function migrateLocal(){try{const result=await api('migrate',{state:M.migrate(App.legacy),confirm:'MIGRAR DADOS LOCAIS'});S=M.migrate(result.state);App.version=result.version;closeModal();render();toast('Dados migrados; cópia local preservada.');}catch(error){toast(error.message);}}

Object.assign(reportNames,{summary:'Resumo Executivo',enrollments:'Matrículas',financial:'Projeção financeira por turma',budget:'Orçamento / Despesas Gerais 2026',audit:'Auditoria de usuários'});
reportData=function(){const t=M.totals(S);if(reportType==='financial'){const rows=M.financialTotals(S,S.activeAcademicYear).rows;return {columns:['Turma','Segmento','Matriculados','Mensalidade','Classificados','Não classificados','Receita bruta conhecida','Descontos','Receita líquida','Ticket médio'],rows:rows.map(x=>[x.name,x.segmentLabel,x.total,x.tuition==null?'Não informada':money(x.tuition),x.classified,x.unclassifiedFinancial,money(x.knownGross),money(x.discounts),money(x.net),x.classified?money(x.ticket):'—'])};}if(reportType==='classes'||reportType==='enrollments')return {columns:['Turma','Capacidade','Rematrículas','Alunos novos','Total','Vagas','Excedentes','Ocupação'],rows:S.classes.map(c=>{const x=statsOf(c);return [c.name,x.capacity,x.re,x.new,x.total,x.vacancies,x.excess,x.occupancy==null?'Sem capacidade':formatPct(x.occupancy)];})};if(reportType==='summary')return {columns:['Indicador','Valor'],rows:[['Total matriculados',t.total],['Novas matrículas',t.new],['Rematrículas',t.re],['Meta de matrículas',t.goal],['Percentual alcançado',formatPct(t.percent)],['Faltam',t.missing],['Vagas',t.vacancies],['Excedentes',t.excess],['Saldo legado a conferir',t.unclassified],['Inadimplência financeira (%)',optionalPercent(S.delinquency.financialPercent)],['Inadimplência contábil (%)',optionalPercent(S.delinquency.accountingPercent)],['Dívida financeira',money(S.delinquency.debt)],['Orçado',money(totals().planned)],['Realizado',money(totals().actual)]]};if(reportType==='budget')return {columns:['Conta','Código','Orçado','Realizado','Disponível','Executado','Atualização'],rows:S.budget.map(x=>[x.category,x.code||'',money(x.budget),money(x.actual),money(x.budget-x.actual),x.budget?formatPct(x.actual/x.budget*100):'—',x.updatedAt||''])};if(reportType==='audit')return {columns:['Usuário','Ação','Módulo','Data/hora','Informação alterada','Anterior','Novo'],rows:(S.audit||[]).map(x=>[x.user,x.action,x.module,new Date(x.date).toLocaleString('pt-BR'),x.field,JSON.stringify(x.before),JSON.stringify(x.after)])};if(reportType==='delinquency')return {columns:['Mês','Financeira (%)','Contábil (%)','Dívida (R$)','Alunos','Responsáveis'],rows:(S.delinquency.monthly||[]).map(x=>[x.month,optionalPercent(x.financialPercent),optionalPercent(x.accountingPercent),money(x.debt),x.students??'—',x.guardians??'—'])};if(reportType==='benefits')return {columns:['Benefício','Tipo','Quantidade','Situação'],rows:S.benefits.map(x=>[x.name,x.type,x.quantity,x.active?'Ativo':'Inativo'])};if(reportType==='requests')return {columns:['Solicitação','Solicitante','Destinatário','Status','Prazo','Reprovação'],rows:S.requests.map(x=>[x.title,x.creatorName||x.requestedBy,x.recipientName||x.owner,labels[x.status],dateLabel(x.due),x.rejectionReason||''])};return {columns:['Nome','Vínculo','WhatsApp','E-mail','Aluno','Turma'],rows:S.guardians.map(x=>[x.name,x.relationship,x.phone,x.email,x.student,findBy(S.classes,x.classId)?.name||x.className||''])};};
reports=function(){if((reportType==='audit'&&!currentUser()?.isAdmin)||(reportType==='financial'&&!financialAllowed()))reportType='summary';const data=reportData();return head('Relatórios Institucionais','Colégio Adventista de Juazeiro · dados atuais dos módulos.',`<div class="head-actions">${btn('Exportar CSV','exportReport()','alt')}${btn('Gerar PDF',"exportInstitutional('pdf')",'alt')}${btn('Exportar Excel',"exportInstitutional('xlsx')",'alt')}${btn('Imprimir','printInstitutional()','alt')}${btn('Backup','exportBackup()','alt')}</div>`)+`<div class="report-control"><label for="reportType">Relatório</label><select id="reportType" onchange="reportType=this.value;render()">${Object.entries(reportNames).filter(([key])=>(key!=='audit'||currentUser()?.isAdmin)&&(key!=='financial'||financialAllowed())).map(([key,name])=>`<option value="${key}" ${key===reportType?'selected':''}>${e(name)}</option>`).join('')}</select></div><div class="letterhead"><b>Colégio Adventista de Juazeiro</b><span>R. Antônio Pedro, 263 - Centro, Juazeiro - BA, 48903-660</span><span>CNPJ: 07.114.699/0047-42</span></div><h2>${e(reportNames[reportType])}</h2>`+table(data.columns,data.rows.map(r=>'<tr>'+r.map(x=>`<td>${e(x??'—')}</td>`).join('')+'</tr>').join(''),data.columns.length,'Sem registros disponíveis.')+`<p class="hint">PDF/Excel requerem o servidor. A logo e a marca-d’água original serão aplicadas após o fornecimento da imagem institucional. Sem imagem, essa pendência é indicada no PDF.</p>`;};
async function exportInstitutional(format){if(App.mode!=='shared')return toast('Geração de PDF/Excel disponível ao entrar no servidor Python.');try{const blob=await api('export',{kind:reportType,title:reportNames[reportType],format,query:$('#tableSearch')?.value||''},true);const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`caj-${reportType}-${localDate()}.${format}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}catch(error){toast(error.message);}}
function printInstitutional(){if(App.mode==='shared'){exportInstitutional('pdf');toast('Abra o PDF gerado para imprimir com cabeçalho e rodapé em todas as páginas.');}else toast('Inicie o servidor para gerar a impressão institucional paginada.');}

const originalCloseProfessional=closeModal;
closeModal=function(){originalCloseProfessional();if(App.mode==='shared'&&App.remotePending)refreshShared().catch(error=>toast(error.message));};
function installFilters(){if(!$('#page table')||page==='users')return;const toolbar=document.createElement('div');toolbar.className='filter-toolbar';toolbar.innerHTML='<label for="tableSearch">Buscar nos registros</label><input id="tableSearch" type="search" placeholder="Digite para filtrar…" oninput="applyTableFilters()"><span id="filterResult" role="status"></span>';$('#page .table-wrap').closest('section').before(toolbar);applyTableFilters();}
render=function(){if(App.mode!=='shared'){showSharedRequired();return;}if(!App.user){showLogin();return;}if(!M.modules.includes(page)||!can(page))page=M.modules.find(module=>can(module))||'unavailable';const views={dashboard,enrollments,classes,financial,benefits,requests,budget,delinquency,guardians,users,reports,tasks,team:()=>head('Equipe','Tarefas da equipe preservadas.')+metrics(['Uilson','Financeiro','Secretaria','Coordenação'].map(person=>[person,S.tasks.filter(x=>x.person===person).length]))};$('#nav').innerHTML=nav.filter(x=>x[1]!=='_'&&can(x[1])).map(x=>`<button class="nav-item ${page===x[1]?'active':''}" title="${e(x[0])}" aria-label="${e(x[0])}" ${page===x[1]?'aria-current="page"':''} data-icon="${x[2]}" onclick="go('${x[1]}')">${x[0]}</button>`).join('');$('#page').innerHTML=(views[page]?views[page]():head('Acesso não atribuído','Solicite ao administrador a liberação dos módulos.'))+`<div class="connection-footer"><span>${connectionLabel()}</span>${btn('Sair','logout()','alt small')}</div>`;$('.profile b').textContent=currentUser()?.name||'Sem sessão';$('.profile small').textContent='Sessão autenticada';$('aside').classList.remove('open');syncMenuState();installFilters();document.title=($('#page h1')?.textContent||'Gestão Escolar')+' · 7&7 CAJ';};
// Preserva Tarefas usando o mesmo mecanismo de gravação e auditoria.
openTask=function(){modal('Nova tarefa',form([['title','Nome da tarefa','text'],['person','Responsável','text'],['date','Prazo','date']])+actions('saveTask()'));};
function saveTask(){commit('tasks','create',s=>{if(!val('title'))throw Error('Informe a tarefa.');s.tasks.push({id:uid(),title:val('title'),person:val('person'),date:val('date'),status:'todo'});});}
cycleTask=function(value){commit('tasks','edit',s=>{const task=findBy(s.tasks,value);task.status=task.status==='todo'?'doing':task.status==='doing'?'done':'todo';});};
// O listener legado de storage não deve substituir dados da base autenticada.
window.addEventListener('storage',event=>{if(event.key===key)event.stopImmediatePropagation();},true);
bootstrapShared();
