const assert=require('node:assert/strict'),M=require('../domain.js');
let count=0;function test(name,fn){fn();count++;console.log('PASS '+name);}
function state(){return M.migrate({classes:[],enrollments:{new:0,re:0,history:[]},users:[]});}
test('Meta oficial e base do relatório 2027',()=>{const s=state(),t=M.totals(s);assert.equal(t.goal,1065);assert.equal(t.total,624);assert.equal(t.missing,441);assert.equal(s.users.length,0);});
test('Estrutura inicial contém as 41 turmas reais sem dupla contagem',()=>{const s=state(),t=M.totals(s);assert.equal(s.classes.length,41);assert.deepEqual(s.classes.slice(0,2).map(c=>c.name),['G2 A','G2 B']);assert.equal(s.classes.at(-1).name,'3º EM');assert.equal(t.capacity,1103);assert.equal(t.new,27);assert.equal(t.re,597);assert.equal(t.total,624);assert.equal(t.vacancies,501);assert.equal(t.excess,22);assert.deepEqual(s.classes.filter(c=>M.classStats(s,c).status==='above').map(c=>c.name),['G4 A','G5 A','4º B','7º A']);});
test('Turmas genéricas vazias são substituídas, mas dados existentes não são removidos',()=>{const generic=M.LEGACY_CORE_CLASSES||['G2','G3','G4','G5','1º Ano','2º Ano','3º Ano','4º Ano','5º Ano','6º Ano','7º Ano','8º Ano','9º Ano','1º Ano do Ensino Médio','2º Ano do Ensino Médio','3º Ano do Ensino Médio'];const clean={schemaVersion:2,meta:1065,classes:generic.map(name=>({id:name,name,capacity:0,students:0,template:true,opening:{new:0,re:0},unclassified:0})),enrollments:{new:0,re:0,history:[],unallocated:{new:0,re:0}}};assert.equal(M.migrate(clean).classes.length,41);const preserved={schemaVersion:2,meta:1065,classes:[{id:'legacy',name:'Turma existente',capacity:30,students:9,opening:{new:0,re:0},unclassified:9}],enrollments:{new:0,re:0,history:[],unallocated:{new:0,re:0}}};assert.equal(M.migrate(preserved).classes.length,1);assert.equal(M.migrate(preserved).classes[0].name,'Turma existente');});
test('Meta configurada é preservada',()=>{const s=M.migrate({meta:700,classes:[],enrollments:{new:0,re:0,history:[]}});assert.equal(M.totals(s).goal,700);M.recalculate(s);assert.equal(s.meta,700);});
test('Saldo legado preservado e incluído no total matriculado',()=>{const original={classes:[{id:1,name:'Fixture',students:30,capacity:40}],enrollments:{new:3,re:2,history:[{id:2,classId:1,type:'new',quantity:3,date:'2026-09-10'},{id:3,classId:1,type:'re',quantity:2,date:'2026-09-10'}]}};const s=M.migrate(original);assert.equal(s.classes[0].unclassified,25);assert.equal(M.totals(s).total,30);assert.equal(original.classes[0].students,30);assert.deepEqual(M.migrate(s),s);});
test('Não classificados participam de vagas e ocupação',()=>{const s=state(),c={id:'c',name:'Fixture',capacity:10,opening:{new:2,re:3},unclassified:6};s.classes=[c];const x=M.classStats(s,c);assert.equal(x.total,11);assert.equal(x.vacancies,0);assert.equal(x.excess,1);assert.equal(x.status,'above');});
test('Contadores globais não vinculados são preservados',()=>{const s=M.migrate({classes:[],enrollments:{new:7,re:9,history:[]}});assert.equal(M.totals(s).total,16);assert.equal(M.totals(s).unallocated,16);});
test('Fronteiras de ocupação',()=>{const s=state(),c={id:'c',name:'Fixture',capacity:100,opening:{new:89,re:0}};s.classes=[c];assert.equal(M.classStats(s,c).status,'normal');c.opening.new=90;assert.equal(M.classStats(s,c).status,'attention');c.opening.new=100;assert.equal(M.classStats(s,c).status,'full');c.opening.new=103;const t=M.classStats(s,c);assert.equal(t.status,'above');assert.equal(t.vacancies,0);assert.equal(t.excess,3);});
test('Editar e excluir lançamento recalcula sem dupla contagem',()=>{const s=state();s.classes=[{id:1,name:'Fixture',capacity:20,opening:{new:0,re:0}}];s.enrollments.history=[{id:'h',classId:1,type:'new',quantity:3,date:'2026-09-10'}];M.recalculate(s);assert.equal(s.enrollments.new,3);s.enrollments.history[0].type='re';M.recalculate(s);assert.equal(s.enrollments.new,0);assert.equal(s.enrollments.re,3);s.enrollments.history=[];M.recalculate(s);assert.equal(M.totals(s).total,0);});
test('Meta atingida e superada mantém percentual real',()=>{const s=state();s.classes=[{id:1,name:'Fixture',capacity:1200,opening:{new:1000,re:100}}];const t=M.totals(s);assert.equal(t.total,1100);assert.equal(t.missing,0);assert.equal(t.excessGoal,35);assert.ok(t.percent>100);});
test('Lívia visualiza Turmas e Vagas e edita somente quantitativos de Matrículas',()=>{const s=M.migrate({users:[{name:'Lívia',permissions:['Editar orçamento','Editar turmas']}]});const u=s.users[0];assert.ok(M.permitted(u,'enrollments','edit'));assert.ok(M.permitted(u,'classes','view'));assert.equal(M.permitted(u,'classes','create'),false);assert.equal(M.permitted(u,'classes','delete'),false);assert.ok(M.permitted(u,'benefits','create'));assert.ok(M.permitted(u,'requests'));for(const m of ['dashboard','budget','users','reports'])assert.equal(M.permitted(u,m),false);assert.equal(M.permitted(u,'benefits','delete'),false);});
test('Receita financeira é calculada por grupo e classificação incompleta não vira sem desconto',()=>{const s=M.migrate({schemaVersion:3,meta:1065,classes:[{id:'g2',name:'G2 A',stage:'Educação Infantil',capacity:18,opening:{new:9,re:0},unclassified:0,students:9}],enrollments:{new:0,re:0,history:[]}});const y=M.financialYear(s,2027);y.classifications.g2={fixed:{noDiscount:1,philanthropic100:1,philanthropic50:1,staffChild100:0,staffChild80:1,workerChild100:0,markingLives45:1},variables:[{id:'v16',percent:16,quantity:1}]};const f=M.financialStats(s,s.classes[0],2027);assert.equal(f.tuition,930.69);assert.equal(f.classified,6);assert.equal(f.unclassifiedFinancial,3);assert.equal(f.fullExempt,1);assert.equal(f.partial,4);assert.equal(Math.round(f.net*100)/100,2875.83);assert.equal(Math.round(f.discounts*100)/100,2708.31);assert.throws(()=>{y.classifications.g2.fixed.noDiscount=10;M.validate(s);},/excede/);});
test('Reprovação exige motivo',()=>{const s=state();s.requests=[{id:1,title:'Fixture',status:'rejected'}];assert.throws(()=>M.validate(s),/motivo/);s.requests[0].rejectionReason='Justificativa de teste';assert.ok(M.validate(s));});
test('Percentuais inválidos e quantidades fracionadas rejeitados',()=>{const s=state();s.delinquency.financialPercent=101;assert.throws(()=>M.validate(s),/Percentuais/);s.delinquency.financialPercent=2.5;s.classes=[{id:1,name:'Fixture',capacity:10.5}];assert.throws(()=>M.validate(s),/Turma/);});
console.log(`${count} testes do modelo aprovados.`);
