// Fixtures existem somente nesta memória isolada; nunca acessam dados do navegador.
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const elements=new Map(),storage=new Map();
function element(selector){if(!elements.has(selector))elements.set(selector,{value:'',innerHTML:'',textContent:'',classList:{add(){},remove(){},toggle(){return false},contains(){return false}},setAttribute(){},querySelectorAll(){return []},querySelector(){return null},addEventListener(){},insertAdjacentHTML(){},focus(){}});return elements.get(selector);}
const context=vm.createContext({console,Date,Math,Number,String,Array,JSON,Object,Set,Blob,URL,setTimeout(){},document:{querySelector(selector){if(selector==='#page table')return null;return element(selector)},addEventListener(){},activeElement:null},window:{addEventListener(){}},localStorage:{getItem(k){return storage.get(k)||null},setItem(k,v){storage.set(k,v)}}});
for(const filename of ['app.js','enhancements.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'..',filename),'utf8'),context,{filename});
const run=code=>vm.runInContext(code,context);
let passed=0;function test(name,callback){callback();passed++;console.log('PASS '+name);}
test('Todas as páginas renderizam sem dados inventados',()=>{for(const name of ['dashboard','enrollments','classes','benefits','requests','budget','delinquency','guardians','users','reports','tasks']){const html=run(name+'()');assert.ok(html.includes('<h1>'));assert.ok(!html.includes('NaN'));}assert.equal(run('students()'),0);assert.equal(run('S.enrollments.history.length'),0);});
test('Migração mantém contadores legados e tarefas vazias',()=>{assert.equal(run("normalizeState({newEnrollments:12,reEnrollments:8,tasks:[]}).enrollments.new"),12);assert.equal(run("normalizeState({tasks:[]}).tasks.length"),0);});
run("S.classes=[{id:1,name:'Teste isolado A',capacity:20,students:5},{id:2,name:'Teste isolado B',capacity:10,students:2}];S.meta=20;render=()=>{};page='enrollments';");
function fields(values){for(const [name,value] of Object.entries(values))element('#f_'+name).value=String(value);}
test('Matrícula alimenta turma, painel, meta e relatório',()=>{fields({class:1,type:'new',quantity:3,date:'2026-09-10'});run('saveEnrollment(null)');assert.equal(run('students()'),10);assert.equal(run('S.enrollments.new'),3);assert.equal(run('totals().missing'),10);assert.equal(run('totals().goalPercent'),50);assert.ok(run('dashboard()').includes('50%'));assert.equal(run("reportType='classes';reportData().rows[0][2]"),8);});
test('Editar transfere turma e tipo sem dupla contagem',()=>{fields({class:2,type:'re',quantity:2,date:'2026-09-10'});run('saveEnrollment(S.enrollments.history[0].id)');assert.equal(run('S.classes[0].students'),5);assert.equal(run('S.classes[1].students'),4);assert.equal(run('S.enrollments.new'),0);assert.equal(run('S.enrollments.re'),2);});
test('Quantidade fracionada ou negativa não altera dados',()=>{const before=run('JSON.stringify(S)');for(const quantity of [1.5,-1,0]){fields({quantity});run('saveEnrollment(null)');assert.equal(run('JSON.stringify(S)'),before);}});
test('Estorno conserva saldo anterior',()=>{run('applyEnrollment(S.enrollments.history[0],-1);S.enrollments.history=[]');assert.equal(run('students()'),7);assert.equal(run('S.enrollments.re'),0);});
test('Vagas por turma não são anuladas por excedentes',()=>{run('S.classes[0].students=23');assert.equal(run('totals().vacancies'),8);assert.equal(run('totals().excess'),3);});
test('Despesa atualiza financeiro, relatório e histórico',()=>{run("page='budget';S.budget=[{id:3,category:'Teste isolado',budget:100,actual:10}]");fields({value:12.35,expenseDate:'2026-09-10',description:'Teste isolado'});run('saveExpense(3)');assert.equal(run('totals().actual'),22.35);assert.equal(run("reportType='budget';reportData().rows[0][2]"),22.35);assert.equal(run('S.budget[0].expenses.length'),1);});
test('Perfil original não ganha administração',()=>{assert.equal(run("canEdit('users')"),false);assert.equal(run("canEdit('enrollments')"),true);assert.equal(run("canEdit('guardians')"),false);});
test('Caracteres de dados são escapados e zero é exibido',()=>{assert.equal(run('e(0)'),'0');assert.equal(run("e('<script>')"),'&lt;script&gt;');});
test('Falha de armazenamento restaura estado confirmado',()=>{run('save()');const before=run('JSON.stringify(S)');context.localStorage.setItem=()=>{throw new Error('quota')};assert.throws(()=>run('S.meta=999;save()'),/quota/);assert.equal(run('JSON.stringify(S)'),before);});
console.log(`${passed} testes aprovados.`);
